#!/bin/sh

zeile() {
	head -$1 erzeuge_neo_de_referenz.1 | tail -1
}


grep -B 1000 "! Keypad" neo_de.xmodmap
grep -A 1000 "! Keypad" neo_de.xmodmap | tail -n +2 > erzeuge_neo_de_referenz.1

anzahl=`wc -l erzeuge_neo_de_referenz.1 | cut -f 1 -d \ `
for i in `seq 1 $anzahl`
do
	anfang=`zeile $i | cut -c 1-3`
	if [ "FOO$anfang" = "FOOkey" ]
	then
		tausche0=`zeile $i | tr [:blank:] " "`
		tausche1=`echo $tausche0 | cut -f 8 -d \ `
		tausche0=`zeile $i | tr [:blank:] " "`
		tausche2=`echo $tausche0 | cut -f 10 -d \ `
		tausche0=`zeile $i | tr [:blank:] " "`
		tausche3=`echo $tausche0 | cut -f 9 -d \ `
		tausche0=`zeile $i | tr [:blank:] " "`
		tausche4=`echo $tausche0 | cut -f 11 -d \ `

		zeile $i | sed s/$tausche1/erzeuge_neo_de_referenz_platzhalter/g | sed s/$tausche2/$tausche1/g | sed s/erzeuge_neo_de_referenz_platzhalter/$tausche2/g | sed s/$tausche3/erzeuge_neo_de_referenz_platzhalter/g | sed s/$tausche4/$tausche4/g | sed s/erzeuge_neo_de_referenz_platzhalter/$tausche4/g
	else
		zeile $i | sed s/Ebene7/erzeuge_neo_de_referenz_platzhalter/g | sed s/Ebene4+Sh/Ebene7/g | sed s/erzeuge_neo_de_referenz_platzhalter/EbeneSh/g | sed s/Ebene6/erzeuge_neo_de_referenz_platzhalter/g | sed s/Ebene4/Ebene6/g | sed s/erzeuge_neo_de_referenz_platzhalter/Ebene4/g | sed s/EbeneSh/Ebene4+Sh/g
	fi
done

rm erzeuge_neo_de_referenz.1
