
# Erweiterung zur Standard-Compose und zur Neo-Compose-Erweiterung zur Verwendung in LyX
#
# Autor: Pascal Hauck <neo at pascalhauck dot de>
#
# Um diese Erweiterung unter Linux zu nutzen, müssen folgende Schritte gegangen werden:
# (Beschreibungen für Windows werden noch ergänzt) 
#
# Schritt 1:
#  Eine neue Compose-Datei (z.B. ~/.XCompose) wird aus folgenden Teilen zusammengestellt:
#   1) Standard-Compose
#   2) Neo-Compose-Erweiterung
#   3) diese Datei
#
# Schritt 2:
#  LyX starten
#  Einige Sekunden warten…
# 
# Schritt 3:
#  Die bisherige Compose-Datei wird wieder hergestellt, bestehend aus:
#   1) Standard-Compose
#   2) Neo-Compose-Erweiterung
#
#
# Man beachte:
#  Alle Programme, die nach der Zusammenstellung der Neo-LyX-Compose gestartet werden,
#  nutzen diese auch. Das heißt, dass z.B. das Zeichen ›…‹ durch ›\\ldots ‹ ersetzt wird.
#  Da dies nicht gewünscht ist, sollte nach dem Starten von LyX erst nann weitere Programme
#  gestartet werden, wenn die bisherige Compose-Datei wieder hergestellt ist und einige
#  Sekunden Zeit vergangen ist.

#configinfo Datei zur direkten Eingabe von Zeichen in LyX

# griechische Buchstaben
<Greek_GAMMA>                                                 : "\\Gamma "
<Greek_DELTA>                                                 : "\\Delta "
<Greek_THETA>                                                 : "\\Theta "
<Greek_LAMBDA>                                                : "\\Lambda "
<Greek_XI>                                                    : "\\Xi "
<Greek_PI>                                                    : "\\Pi "
<Greek_SIGMA>                                                 : "\\Sigma "
<Greek_PHI>                                                   : "\\Phi "
<Greek_CHI>                                                   : "\\Chi "
<Greek_PSI>                                                   : "\\Psi "
<Greek_OMEGA>                                                 : "\\Omega "
<Greek_alpha>                                                 : "\\alpha "
<Greek_beta>                                                  : "\\beta "
<Greek_gamma>                                                 : "\\gamma "
<Greek_delta>                                                 : "\\delta "
<Greek_epsilon>                                               : "\\varepsilon "
<Greek_zeta>                                                  : "\\zeta "
<Greek_eta>                                                   : "\\eta "
<Greek_theta>                                                 : "\\theta "
<Greek_iota>                                                  : "\\iota "
<Greek_kappa>                                                 : "\\kappa "
<Greek_lambda>                                                : "\\lambda "
<Greek_mu>                                                    : "\\mu "
<Greek_nu>                                                    : "\\nu "
<Greek_xi>                                                    : "\\xi "
<Greek_pi>                                                    : "\\pi "
<Greek_rho>                                                   : "\\rho "
<Greek_sigma>                                                 : "\\sigma "
<Greek_tau>                                                   : "\\tau "
<Greek_upsilon>                                               : "\\upsilon "
<Greek_phi>                                                   : "\\varphi "
<U03D5>                                                       : "\\phi "
<Greek_chi>                                                   : "\\chi "
<Greek_psi>                                                   : "\\psi "
<Greek_omega>                                                 : "\\omega "
<U03D1>                                                       : "\\vartheta "
<U03F0>                                                       : "\\varkappa "
<U03F5>                                                       : "\\epsilon "
<U03F1>                                                       : "\\varrho "

# hoch- und tiefgestellte Zeichen
<dead_circumflex> <1>                                         : "^1 "
<dead_circumflex> <2>                                         : "^2 "
<dead_circumflex> <3>                                         : "^3 "
<dead_circumflex> <4>                                         : "^4 "
<dead_circumflex> <5>                                         : "^5 "
<dead_circumflex> <6>                                         : "^6 "
<dead_circumflex> <7>                                         : "^7 "
<dead_circumflex> <8>                                         : "^8 "
<dead_circumflex> <9>                                         : "^9 "
<zerosubscript>                                               : "_0 "
<onesubscript>                                                : "_1 "
<twosubscript>                                                : "_2 "
<threesubscript>                                              : "_3 "
<onesuperior>                                                 : "^1 "
<twosuperior>                                                 : "^2 "
<threesuperior>                                               : "^3 "

# Operationen
<U22C5>                                                       : "\\cdot "
<periodcentered>                                              : "\\cdot "
<multiply>                                                    : "\\times "
<radical>                                                     : "\\sqrt "
<integral>                                                    : "\\int "
<KP_Divide>                                                   : "\\frac "
<Multi_key> <d> <x>                                           : "\\mathrm d x"
<plusminus>                                                   : "\\pm "
<elementof>                                                   : "\\in "
<U226A>                                                       : "\\ll "
<U226B>                                                       : "\\gg "
<U2295>                                                       : "\\oplus "
<U2299>                                                       : "\\odot "
<U2296>                                                       : "\\ominus "
<U2300>                                                       : "\\oslash "
<U2216>                                                       : "\\setminus "

# Pfeile, Gleichheitszeichen und ähnliches
<U21D2>                                                       : "\\Rightarrow "
<ifonlyif>                                                    : "\\Leftrightarrow "
<U21D0>                                                       : "\\Leftarrow "
<rightarrow>                                                  : "\\rightarrow "
<leftarrow>                                                   : "\\leftarrow "
<approxeq>                                                    : "\\approx "
<rightarrow>                                                  : "\\to "
<notequal>                                                    : "\\neq "
<identical>                                                   : "\\equiv "
<includedin>                                                  : "\\subset "
<intersection>                                                : "\\cap "
<union>                                                       : "\\cup "
<dead_stroke> <elementof>                                     : "\\notin "
<lessthanequal>                                               : "\\leq "
<greaterthanequal>                                            : "\\geq "
<Multi_key> <grater> <equal>                                  : "\\geq "
<Multi_key> <equal> <grater>                                  : "\\geq "
<Multi_key> <lower> <equal>                                   : "\\leq "
<Multi_key> <equal> <lower>                                   : "\\leq "
<Multi_key> <includein> <equal>                               : "\\subseteq "
<Multi_key> <equal> <includein>                               : "\\subseteq "
<dead_macron> <includes>                                      : "\\subseteq "
<asciitilde>                                                  : "\\sim "


# Zahlen und Mengen
<Multi_key> <elementof> <R>                                   : "\\in \\mathbb R "
<Multi_key> <elementof> <N>                                   : "\\in \\mathbb N "
<Multi_key> <elementof> <Z>                                   : "\\in \\mathbb Z "
<Multi_key> <elementof> <Q>                                   : "\\in \\mathbb Q "
<Multi_key> <elementof> <C>                                   : "\\in \\mathbb C "
<U211D>                                                       : "\\mathbb R "
<U2124>                                                       : "\\mathbb Z "
<U211A>                                                       : "\\mathbb Q "
<U2115>                                                       : "\\mathbb N "
<U2102>                                                       : "\\mathbb C "
<infinity>                                                    : "\\infty "

# weitere Zeichen
<Multi_key> <l> <i> <m>                                       : "\\lim _"
<\Greek_SIGMA>                                                : "\\sum _"
<bar>                                                         : "\\mid "
<Multi_key> <d> <f> <d> <x>                                   : "\\frac \\mathrm d f  \\mathrm d x "
<U2200>                                                       : "\\forall "
<U2203>                                                       : "\\exists "
<U222E>                                                       : "\\oint "
<jot>                                                         : "\\circ "
<partialderivative>                                           : "\\partial "
<nabla>                                                       : "\\nabla "
<variation>                                                   : "\\propto "
<U20D7>                                                       : "\\vec "
<ellipsis>                                                    : "\\ldots "
<U2221>                                                       : "\\measuredangle "
<U2225>                                                       : "\\parallel "
<downtack>                                                    : "\\bot "
<dead_stroke> <U2203>                                         : "\\nexists "
<Multi_key> <slash> <U2203>                                   : "\\nexists "
<Multi_key> <U2203> <dead_stroke> <dead_stroke>               : "\\nexists "
<Multi_key> <Greek_SIGMA> <Greek_SIGMA>                       : "\\sum "
<Multi_key> <r> <m>                                           : "\\mathrm "
<emptyset>                                                    : "\\empty "
<dead_circumflex> <dagger>                                    : "^\\dagger "
<logicalor>                                                   : "\\vee "
<logicaland>                                                  : "\\wedge "
