Compose_neo_math.neo: Compose.neo Compose_math_and_physics.neo
	cat Compose.neo Compose_math_and_physics.neo > Compose_neo_math.neo
	echo -e "\n# End of Definitions by Neo keyboard layout" >> Compose_neo_math.neo

Compone_neo_greek.neo: Compose.neo Compose_greek.neo
	cat Compose.neo Compose_greek.neo > Compone_neo_greek.neo
	echo -e "\n# End of Definitions by Neo keyboard layout" >> Compone_neo_greek.neo

Compone_neo_rom.neo: Compose.neo Compose_many_roman_numericals.neo
	cat Compose.neo Compose_many_roman_numericals.neo > Compone_neo_rom.neo
	echo -e "\n# End of Definitions by Neo keyboard layout" >> Compone_neo_rom.neo
