#configinfo Neo-Diakritika

# Ohne dieses Modul hat man die Standard-en_US-Deadkey-Diakritika-Kombinationen:
# <dead_foo> <dead_foo> -----> FOO
# <dead_foo> <space> -----> FOO
# <dead_foo> <nobreakspace> -----> COMBINING FOO
#
# Mit diesem Modul hat man Folgende Belegung:
# <dead_foo> <dead_foo> -----> COMBINING FOO
# <dead_foo> <space> -----> FOO
# <dead_foo> <nobreakspace> -----> FOO

<dead_circumflex> <nobreakspace>           : "ˆ"   U02C6 # MODIFIER LETTER CIRCUMFLEX ACCENT
<dead_caron> <nobreakspace>                : "ˇ"   U02C7 # CARON
<dead_breve> <nobreakspace>                : "˘"   U02D8 # BREVE
<dead_acute> <nobreakspace>                : "´"   U00B4 # ACUTE ACCENT
<dead_grave> <nobreakspace>                : "`"   U0060 # GRAVE ACCENT
<dead_cedilla> <nobreakspace>              : "¸"   U00B8 # CEDILLA
<dead_abovedot> <nobreakspace>             : "˙"   U02D9 # DOT ABOVE
<dead_abovering> <nobreakspace>            : "˚"   U02DA # RING ABOVE
<dead_tilde> <nobreakspace>                : "˜"   U02DC # SMALL TILDE
<dead_macron> <nobreakspace>               : "¯"   U00AF # MACRON
<dead_diaeresis> <nobreakspace>            : "¨"   U00A8 # DIAERESIS
<dead_stroke> <nobreakspace>               : "/"   U002F # SOLIDUS
<dead_doubleacute> <nobreakspace>          : "˝"   U02DD # DOUBLE ACUTE ACCENT
<dead_psili> <nobreakspace>                : "᾿"   U1FBF # GREEK PSILI
<dead_dasia> <nobreakspace>                : "῾"   U1FFE # GREEK DASIA
<dead_belowdot> <nobreakspace>             : "."   U002E # FULL STOP


# combining characters
<dead_circumflex> <dead_circumflex>        : "̂"   U0302 # COMBINING CIRCUMFLEX ACCENT
<dead_caron> <dead_caron>                  : "̌"   U030c # COMBINING CARON
<dead_breve> <dead_breve>                  : "̆"   U0306 # COMBINING BREVE
<dead_acute> <dead_acute>                  : "́"   U0301 # COMBINING ACUTE ACCENT
<dead_grave> <dead_grave>                  : "̀"   U0300 # COMBINING GRAVE ACCENT
<dead_cedilla> <dead_cedilla>              : "̧"   U0327 # COMBINING CEDILLA
<dead_abovedot> <dead_abovedot>            : "̇"   U0307 # COMBINING DOT ABOVE
<dead_abovering> <dead_abovering>          : "̊"   U030A # COMBINING RING ABOVE
<dead_tilde> <dead_tilde>                  : "̃"   U0303 # COMBINING TILDE
<dead_macron> <dead_macron>                : "̄"   U0304 # COMBINING MACRON
<dead_diaeresis> <dead_diaeresis>          : "̈"   U0308 # COMBINING DIAERESIS
<dead_stroke> <dead_stroke>                : "̷"   U0337 # COMBINING SHORT SOLIDUS OVERLAY
<dead_doubleacute> <dead_doubleacute>      : "̋"   U030B # COMBINING DOUBLE ACUTE ACCENT
<dead_psili> <dead_psili>                  : "̓"   U0313 # COMBINING COMMA ABOVE
<dead_dasia> <dead_dasia>                  : "̔"   U0314 # COMBINING REVERSED COMMA ABOVE
<U02F5> <U02F5>                            : "̏"   U030F # COMBINING DOUBLE GRAVE ACCENT
<U02DE> <U02DE>                            : "˞"   U02DE # MODIFIER LETTER RHOTIC HOOK
#<dead_belowdot> <dead_belowdot>            : "̣"   U0323 # COMBINING DOT BELOW # already in en_US.utf8
<Multi_key> <underscore> <underscore>      : "̲"   U0332 # COMBINING LOW LINE
