#configinfo Griechische Buchstaben mit Akzenten (A ἀ)


# additional Definitions by Neo keyboard layout - greek letters

# capital greek letters
<Multi_key> <G> <A>                      : "Α"   U0391 # GREEK CAPITAL LETTER ALPHA
<Multi_key> <g> <A>                      : "Α"   U0391 # GREEK CAPITAL LETTER ALPHA
<Multi_key> <G> <B>                      : "Β"   U0392 # GREEK CAPITAL LETTER BETA
<Multi_key> <g> <B>                      : "Β"   U0392 # GREEK CAPITAL LETTER BETA
<Multi_key> <G> <E>                      : "Ε"   U0395 # GREEK CAPITAL LETTER EPSILON
<Multi_key> <g> <E>                      : "Ε"   U0395 # GREEK CAPITAL LETTER EPSILON
<Multi_key> <G> <Z>                      : "Ζ"   U0396 # GREEK CAPITAL LETTER ZETA
<Multi_key> <g> <Z>                      : "Ζ"   U0396 # GREEK CAPITAL LETTER ZETA
<Multi_key> <G> <H>                      : "Η"   U0397 # GREEK CAPITAL LETTER ETA
<Multi_key> <g> <H>                      : "Η"   U0397 # GREEK CAPITAL LETTER ETA
<Multi_key> <G> <Adiaeresis>             : "Η"   U0397 # GREEK CAPITAL LETTER ETA
<Multi_key> <g> <Adiaeresis>             : "Η"   U0397 # GREEK CAPITAL LETTER ETA
<Multi_key> <G> <I>                      : "Ι"   U0399 # GREEK CAPITAL LETTER IOTA
<Multi_key> <g> <I>                      : "Ι"   U0399 # GREEK CAPITAL LETTER IOTA
<Multi_key> <G> <K>                      : "Κ"   U039A # GREEK CAPITAL LETTER KAPPA
<Multi_key> <g> <K>                      : "Κ"   U039A # GREEK CAPITAL LETTER KAPPA
<Multi_key> <G> <M>                      : "Μ"   U039C # GREEK CAPITAL LETTER MU
<Multi_key> <g> <M>                      : "Μ"   U039C # GREEK CAPITAL LETTER MU
<Multi_key> <G> <N>                      : "Ν"   U039D # GREEK CAPITAL LETTER NU
<Multi_key> <g> <N>                      : "Ν"   U039D # GREEK CAPITAL LETTER NU
<Multi_key> <G> <O>                      : "Ο"   U039F # GREEK CAPITAL LETTER OMICRON
<Multi_key> <g> <O>                      : "Ο"   U039F # GREEK CAPITAL LETTER OMICRON
<Multi_key> <G> <P>                      : "Ρ"   U03A1 # GREEK CAPITAL LETTER RHO
<Multi_key> <g> <P>                      : "Ρ"   U03A1 # GREEK CAPITAL LETTER RHO
<Multi_key> <G> <R>                      : "Ρ"   U03A1 # GREEK CAPITAL LETTER RHO
<Multi_key> <g> <R>                      : "Ρ"   U03A1 # GREEK CAPITAL LETTER RHO
<Multi_key> <G> <T>                      : "Τ"   U03A4 # GREEK CAPITAL LETTER TAU
<Multi_key> <g> <T>                      : "Τ"   U03A4 # GREEK CAPITAL LETTER TAU
<Multi_key> <G> <Y>                      : "Υ"   U03A5 # GREEK CAPITAL LETTER UPSILON
<Multi_key> <g> <Y>                      : "Υ"   U03A5 # GREEK CAPITAL LETTER UPSILON
<Multi_key> <G> <X>                      : "Χ"   U03A7 # GREEK CAPITAL LETTER CHI
<Multi_key> <g> <X>                      : "Χ"   U03A7 # GREEK CAPITAL LETTER CHI
<U02DE> <Multi_key> <G> <Y>              : "ϒ"   U03D2 # GREEK UPSILON WITH HOOK SYMBOL
<U02DE> <Multi_key> <g> <Y>              : "ϒ"   U03A5 # GREEK UPSILON WITH HOOK SYMBOL

# greek letters with diacritical marks
<dead_psili> <Greek_alpha>                               : "ἀ"   U1F00 # GREEK SMALL LETTER ALPHA WITH PSILI
<dead_dasia> <Greek_alpha>                               : "ἁ"   U1F01 # GREEK SMALL LETTER ALPHA WITH DASIA
<dead_psili> <dead_grave> <Greek_alpha>                  : "ἂ"   U1F02 # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Greek_alpha>                  : "ἂ"   U1F02 # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Greek_alpha>                  : "ἃ"   U1F03 # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Greek_alpha>                  : "ἃ"   U1F03 # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Greek_alpha>                  : "ἄ"   U1F04 # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Greek_alpha>                  : "ἄ"   U1F04 # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Greek_alpha>                  : "ἅ"   U1F05 # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Greek_alpha>                  : "ἅ"   U1F05 # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA
<dead_psili> <dead_tilde> <Greek_alpha>                  : "ἆ"   U1F06 # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI
<dead_tilde> <dead_psili> <Greek_alpha>                  : "ἆ"   U1F06 # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI
<dead_dasia> <dead_tilde> <Greek_alpha>                  : "ἇ"   U1F07 # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Greek_alpha>                  : "ἇ"   U1F07 # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI
<dead_psili> <Greek_epsilon>                             : "ἐ"   U1F10 # GREEK SMALL LETTER EPSILON WITH PSILI
<dead_dasia> <Greek_epsilon>                             : "ἑ"   U1F11 # GREEK SMALL LETTER EPSILON WITH DASIA
<dead_psili> <dead_grave> <Greek_epsilon>                : "ἒ"   U1F12 # GREEK SMALL LETTER EPSILON WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Greek_epsilon>                : "ἒ"   U1F12 # GREEK SMALL LETTER EPSILON WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Greek_epsilon>                : "ἓ"   U1F13 # GREEK SMALL LETTER EPSILON WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Greek_epsilon>                : "ἓ"   U1F13 # GREEK SMALL LETTER EPSILON WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Greek_epsilon>                : "ἔ"   U1F14 # GREEK SMALL LETTER EPSILON WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Greek_epsilon>                : "ἔ"   U1F14 # GREEK SMALL LETTER EPSILON WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Greek_epsilon>                : "ἕ"   U1F15 # GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Greek_epsilon>                : "ἕ"   U1F15 # GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA
<dead_psili> <Greek_eta>                                 : "ἠ"   U1F20 # GREEK SMALL LETTER ETA WITH PSILI
<dead_dasia> <Greek_eta>                                 : "ἡ"   U1F21 # GREEK SMALL LETTER ETA WITH DASIA
<dead_psili> <dead_grave> <Greek_eta>                    : "ἢ"   U1F22 # GREEK SMALL LETTER ETA WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Greek_eta>                    : "ἢ"   U1F22 # GREEK SMALL LETTER ETA WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Greek_eta>                    : "ἣ"   U1F23 # GREEK SMALL LETTER ETA WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Greek_eta>                    : "ἣ"   U1F23 # GREEK SMALL LETTER ETA WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Greek_eta>                    : "ἤ"   U1F24 # GREEK SMALL LETTER ETA WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Greek_eta>                    : "ἤ"   U1F24 # GREEK SMALL LETTER ETA WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Greek_eta>                    : "ἥ"   U1F25 # GREEK SMALL LETTER ETA WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Greek_eta>                    : "ἥ"   U1F25 # GREEK SMALL LETTER ETA WITH DASIA AND OXIA
<dead_psili> <dead_tilde> <Greek_eta>                    : "ἦ"   U1F26 # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI
<dead_tilde> <dead_psili> <Greek_eta>                    : "ἦ"   U1F26 # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI
<dead_dasia> <dead_tilde> <Greek_eta>                    : "ἧ"   U1F27 # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Greek_eta>                    : "ἧ"   U1F27 # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI
<dead_psili> <Greek_iota>                                : "ἰ"   U1F30 # GREEK SMALL LETTER IOTA WITH PSILI
<dead_dasia> <Greek_iota>                                : "ἱ"   U1F31 # GREEK SMALL LETTER IOTA WITH DASIA
<dead_psili> <dead_grave> <Greek_iota>                   : "ἲ"   U1F32 # GREEK SMALL LETTER IOTA WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Greek_iota>                   : "ἲ"   U1F32 # GREEK SMALL LETTER IOTA WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Greek_iota>                   : "ἳ"   U1F33 # GREEK SMALL LETTER IOTA WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Greek_iota>                   : "ἳ"   U1F33 # GREEK SMALL LETTER IOTA WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Greek_iota>                   : "ἴ"   U1F34 # GREEK SMALL LETTER IOTA WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Greek_iota>                   : "ἴ"   U1F34 # GREEK SMALL LETTER IOTA WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Greek_iota>                   : "ἵ"   U1F35 # GREEK SMALL LETTER IOTA WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Greek_iota>                   : "ἵ"   U1F35 # GREEK SMALL LETTER IOTA WITH DASIA AND OXIA
<dead_psili> <dead_tilde> <Greek_iota>                   : "ἶ"   U1F36 # GREEK SMALL LETTER IOTA WITH PSILI AND PERISPOMENI
<dead_tilde> <dead_psili> <Greek_iota>                   : "ἶ"   U1F36 # GREEK SMALL LETTER IOTA WITH PSILI AND PERISPOMENI
<dead_dasia> <dead_tilde> <Greek_iota>                   : "ἷ"   U1F37 # GREEK SMALL LETTER IOTA WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Greek_iota>                   : "ἷ"   U1F37 # GREEK SMALL LETTER IOTA WITH DASIA AND PERISPOMENI
<dead_psili> <Greek_omicron>                             : "ὀ"   U1F40 # GREEK SMALL LETTER OMICRON WITH PSILI
<dead_dasia> <Greek_omicron>                             : "ὁ"   U1F41 # GREEK SMALL LETTER OMICRON WITH DASIA
<dead_psili> <dead_grave> <Greek_omicron>                : "ὂ"   U1F42 # GREEK SMALL LETTER OMICRON WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Greek_omicron>                : "ὂ"   U1F42 # GREEK SMALL LETTER OMICRON WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Greek_omicron>                : "ὃ"   U1F43 # GREEK SMALL LETTER OMICRON WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Greek_omicron>                : "ὃ"   U1F43 # GREEK SMALL LETTER OMICRON WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Greek_omicron>                : "ὄ"   U1F44 # GREEK SMALL LETTER OMICRON WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Greek_omicron>                : "ὄ"   U1F44 # GREEK SMALL LETTER OMICRON WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Greek_omicron>                : "ὅ"   U1F45 # GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Greek_omicron>                : "ὅ"   U1F45 # GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA
<dead_psili> <Greek_upsilon>                             : "ὐ"   U1F50 # GREEK SMALL LETTER UPSILON WITH PSILI
<dead_dasia> <Greek_upsilon>                             : "ὑ"   U1F51 # GREEK SMALL LETTER UPSILON WITH DASIA
<dead_psili> <dead_grave> <Greek_upsilon>                : "ὒ"   U1F52 # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Greek_upsilon>                : "ὒ"   U1F52 # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Greek_upsilon>                : "ὓ"   U1F53 # GREEK SMALL LETTER UPSILON WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Greek_upsilon>                : "ὓ"   U1F53 # GREEK SMALL LETTER UPSILON WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Greek_upsilon>                : "ὔ"   U1F54 # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Greek_upsilon>                : "ὔ"   U1F54 # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Greek_upsilon>                : "ὕ"   U1F55 # GREEK SMALL LETTER UPSILON WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Greek_upsilon>                : "ὕ"   U1F55 # GREEK SMALL LETTER UPSILON WITH DASIA AND OXIA
<dead_psili> <dead_tilde> <Greek_upsilon>                : "ὖ"   U1F56 # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
<dead_tilde> <dead_psili> <Greek_upsilon>                : "ὖ"   U1F56 # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
<dead_dasia> <dead_tilde> <Greek_upsilon>                : "ὗ"   U1F57 # GREEK SMALL LETTER UPSILON WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Greek_upsilon>                : "ὗ"   U1F57 # GREEK SMALL LETTER UPSILON WITH DASIA AND PERISPOMENI
<dead_psili> <Greek_omega>                               : "ὠ"   U1F60 # GREEK SMALL LETTER OMEGA WITH PSILI
<dead_dasia> <Greek_omega>                               : "ὡ"   U1F61 # GREEK SMALL LETTER OMEGA WITH DASIA
<dead_psili> <dead_grave> <Greek_omega>                  : "ὢ"   U1F62 # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Greek_omega>                  : "ὢ"   U1F62 # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Greek_omega>                  : "ὣ"   U1F63 # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Greek_omega>                  : "ὣ"   U1F63 # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Greek_omega>                  : "ὤ"   U1F64 # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Greek_omega>                  : "ὤ"   U1F64 # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Greek_omega>                  : "ὥ"   U1F65 # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Greek_omega>                  : "ὥ"   U1F65 # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA
<dead_psili> <dead_tilde> <Greek_omega>                  : "ὦ"   U1F66 # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI
<dead_tilde> <dead_psili> <Greek_omega>                  : "ὦ"   U1F66 # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI
<dead_dasia> <dead_tilde> <Greek_omega>                  : "ὧ"   U1F67 # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Greek_omega>                  : "ὧ"   U1F67 # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI
<dead_grave> <Greek_alpha>                               : "ὰ"   U1F70 # GREEK SMALL LETTER ALPHA WITH VARIA
<dead_grave> <Greek_epsilon>                             : "ὲ"   U1F72 # GREEK SMALL LETTER EPSILON WITH VARIA
<dead_grave> <Greek_eta>                                 : "ὴ"   U1F74 # GREEK SMALL LETTER ETA WITH VARIA
<dead_grave> <Greek_iota>                                : "ὶ"   U1F76 # GREEK SMALL LETTER IOTA WITH VARIA
<dead_grave> <Greek_omicron>                             : "ὸ"   U1F78 # GREEK SMALL LETTER OMICRON WITH VARIA
<dead_grave> <Greek_upsilon>                             : "ὺ"   U1F7A # GREEK SMALL LETTER UPSILON WITH VARIA
<dead_grave> <Greek_omega>                               : "ὼ"   U1F7C # GREEK SMALL LETTER OMEGA WITH VARIA
<dead_psili> <dead_cedilla> <Greek_alpha>                : "ᾀ"   U1F80 # GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <Greek_alpha>                : "ᾀ"   U1F80 # GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <Greek_alpha>                : "ᾁ"   U1F81 # GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <Greek_alpha>                : "ᾁ"   U1F81 # GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
<dead_psili> <dead_grave> <dead_cedilla> <Greek_alpha>   : "ᾂ"   U1F82 # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_grave> <Greek_alpha>   : "ᾂ"   U1F82 # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_psili> <dead_cedilla> <Greek_alpha>   : "ᾂ"   U1F82 # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_psili> <Greek_alpha>   : "ᾂ"   U1F82 # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_grave> <Greek_alpha>   : "ᾂ"   U1F82 # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_psili> <Greek_alpha>   : "ᾂ"   U1F82 # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_dasia> <dead_grave> <dead_cedilla> <Greek_alpha>   : "ᾃ"   U1F83 # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_grave> <Greek_alpha>   : "ᾃ"   U1F83 # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_dasia> <dead_cedilla> <Greek_alpha>   : "ᾃ"   U1F83 # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_dasia> <Greek_alpha>   : "ᾃ"   U1F83 # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_grave> <Greek_alpha>   : "ᾃ"   U1F83 # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_dasia> <Greek_alpha>   : "ᾃ"   U1F83 # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_psili> <dead_acute> <dead_cedilla> <Greek_alpha>   : "ᾄ"   U1F84 # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_acute> <Greek_alpha>   : "ᾄ"   U1F84 # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_psili> <dead_cedilla> <Greek_alpha>   : "ᾄ"   U1F84 # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_psili> <Greek_alpha>   : "ᾄ"   U1F84 # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_acute> <Greek_alpha>   : "ᾄ"   U1F84 # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_psili> <Greek_alpha>   : "ᾄ"   U1F84 # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_dasia> <dead_acute> <dead_cedilla> <Greek_alpha>   : "ᾅ"   U1F85 # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_acute> <Greek_alpha>   : "ᾅ"   U1F85 # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_dasia> <dead_cedilla> <Greek_alpha>   : "ᾅ"   U1F85 # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_dasia> <Greek_alpha>   : "ᾅ"   U1F85 # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_acute> <Greek_alpha>   : "ᾅ"   U1F85 # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_dasia> <Greek_alpha>   : "ᾅ"   U1F85 # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_psili> <dead_tilde> <dead_cedilla> <Greek_alpha>   : "ᾆ"   U1F86 # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_tilde> <Greek_alpha>   : "ᾆ"   U1F86 # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_psili> <dead_cedilla> <Greek_alpha>   : "ᾆ"   U1F86 # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_psili> <Greek_alpha>   : "ᾆ"   U1F86 # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_tilde> <Greek_alpha>   : "ᾆ"   U1F86 # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_psili> <Greek_alpha>   : "ᾆ"   U1F86 # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_dasia> <dead_tilde> <dead_cedilla> <Greek_alpha>   : "ᾇ"   U1F87 # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_tilde> <Greek_alpha>   : "ᾇ"   U1F87 # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_dasia> <dead_cedilla> <Greek_alpha>   : "ᾇ"   U1F87 # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_dasia> <Greek_alpha>   : "ᾇ"   U1F87 # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_tilde> <Greek_alpha>   : "ᾇ"   U1F87 # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_dasia> <Greek_alpha>   : "ᾇ"   U1F87 # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <Greek_eta>                  : "ᾐ"   U1F90 # GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <Greek_eta>                  : "ᾐ"   U1F90 # GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <Greek_eta>                  : "ᾑ"   U1F91 # GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <Greek_eta>                  : "ᾑ"   U1F91 # GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
<dead_psili> <dead_grave> <dead_cedilla> <Greek_eta>     : "ᾒ"   U1F92 # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_grave> <Greek_eta>     : "ᾒ"   U1F92 # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_psili> <dead_cedilla> <Greek_eta>     : "ᾒ"   U1F92 # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_psili> <Greek_eta>     : "ᾒ"   U1F92 # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_grave> <Greek_eta>     : "ᾒ"   U1F92 # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_psili> <Greek_eta>     : "ᾒ"   U1F92 # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_dasia> <dead_grave> <dead_cedilla> <Greek_eta>     : "ᾓ"   U1F93 # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_grave> <Greek_eta>     : "ᾓ"   U1F93 # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_dasia> <dead_cedilla> <Greek_eta>     : "ᾓ"   U1F93 # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_dasia> <Greek_eta>     : "ᾓ"   U1F93 # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_grave> <Greek_eta>     : "ᾓ"   U1F93 # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_dasia> <Greek_eta>     : "ᾓ"   U1F93 # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_psili> <dead_acute> <dead_cedilla> <Greek_eta>     : "ᾔ"   U1F94 # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_acute> <Greek_eta>     : "ᾔ"   U1F94 # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_psili> <dead_cedilla> <Greek_eta>     : "ᾔ"   U1F94 # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_psili> <Greek_eta>     : "ᾔ"   U1F94 # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_acute> <Greek_eta>     : "ᾔ"   U1F94 # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_psili> <Greek_eta>     : "ᾔ"   U1F94 # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_dasia> <dead_acute> <dead_cedilla> <Greek_eta>     : "ᾕ"   U1F95 # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_acute> <Greek_eta>     : "ᾕ"   U1F95 # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_dasia> <dead_cedilla> <Greek_eta>     : "ᾕ"   U1F95 # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_dasia> <Greek_eta>     : "ᾕ"   U1F95 # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_acute> <Greek_eta>     : "ᾕ"   U1F95 # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_dasia> <Greek_eta>     : "ᾕ"   U1F95 # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_psili> <dead_tilde> <dead_cedilla> <Greek_eta>     : "ᾖ"   U1F96 # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_tilde> <Greek_eta>     : "ᾖ"   U1F96 # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_psili> <dead_cedilla> <Greek_eta>     : "ᾖ"   U1F96 # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_psili> <Greek_eta>     : "ᾖ"   U1F96 # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_tilde> <Greek_eta>     : "ᾖ"   U1F96 # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_psili> <Greek_eta>     : "ᾖ"   U1F96 # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_dasia> <dead_tilde> <dead_cedilla> <Greek_eta>     : "ᾗ"   U1F97 # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_tilde> <Greek_eta>     : "ᾗ"   U1F97 # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_dasia> <dead_cedilla> <Greek_eta>     : "ᾗ"   U1F97 # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_dasia> <Greek_eta>     : "ᾗ"   U1F97 # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_tilde> <Greek_eta>     : "ᾗ"   U1F97 # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_dasia> <Greek_eta>     : "ᾗ"   U1F97 # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <Greek_omega>                : "ᾠ"   U1FA0 # GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <Greek_omega>                : "ᾠ"   U1FA0 # GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <Greek_omega>                : "ᾡ"   U1FA1 # GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <Greek_omega>                : "ᾡ"   U1FA1 # GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
<dead_psili> <dead_grave> <dead_cedilla> <Greek_omega>   : "ᾢ"   U1FA2 # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_grave> <Greek_omega>   : "ᾢ"   U1FA2 # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_psili> <dead_cedilla> <Greek_omega>   : "ᾢ"   U1FA2 # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_psili> <Greek_omega>   : "ᾢ"   U1FA2 # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_grave> <Greek_omega>   : "ᾢ"   U1FA2 # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_psili> <Greek_omega>   : "ᾢ"   U1FA2 # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
<dead_dasia> <dead_grave> <dead_cedilla> <Greek_omega>   : "ᾣ"   U1FA3 # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_grave> <Greek_omega>   : "ᾣ"   U1FA3 # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_dasia> <dead_cedilla> <Greek_omega>   : "ᾣ"   U1FA3 # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_dasia> <Greek_omega>   : "ᾣ"   U1FA3 # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_grave> <Greek_omega>   : "ᾣ"   U1FA3 # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_dasia> <Greek_omega>   : "ᾣ"   U1FA3 # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
<dead_psili> <dead_acute> <dead_cedilla> <Greek_omega>   : "ᾤ"   U1FA4 # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_acute> <Greek_omega>   : "ᾤ"   U1FA4 # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_psili> <dead_cedilla> <Greek_omega>   : "ᾤ"   U1FA4 # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_psili> <Greek_omega>   : "ᾤ"   U1FA4 # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_acute> <Greek_omega>   : "ᾤ"   U1FA4 # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_psili> <Greek_omega>   : "ᾤ"   U1FA4 # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
<dead_dasia> <dead_acute> <dead_cedilla> <Greek_omega>   : "ᾥ"   U1FA5 # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_acute> <Greek_omega>   : "ᾥ"   U1FA5 # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_dasia> <dead_cedilla> <Greek_omega>   : "ᾥ"   U1FA5 # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_dasia> <Greek_omega>   : "ᾥ"   U1FA5 # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_acute> <Greek_omega>   : "ᾥ"   U1FA5 # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_dasia> <Greek_omega>   : "ᾥ"   U1FA5 # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
<dead_psili> <dead_tilde> <dead_cedilla> <Greek_omega>   : "ᾦ"   U1FA6 # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_tilde> <Greek_omega>   : "ᾦ"   U1FA6 # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_psili> <dead_cedilla> <Greek_omega>   : "ᾦ"   U1FA6 # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_psili> <Greek_omega>   : "ᾦ"   U1FA6 # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_tilde> <Greek_omega>   : "ᾦ"   U1FA6 # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_psili> <Greek_omega>   : "ᾦ"   U1FA6 # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
<dead_dasia> <dead_tilde> <dead_cedilla> <Greek_omega>   : "ᾧ"   U1FA7 # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_tilde> <Greek_omega>   : "ᾧ"   U1FA7 # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_dasia> <dead_cedilla> <Greek_omega>   : "ᾧ"   U1FA7 # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_dasia> <Greek_omega>   : "ᾧ"   U1FA7 # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_tilde> <Greek_omega>   : "ᾧ"   U1FA7 # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_dasia> <Greek_omega>   : "ᾧ"   U1FA7 # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
<dead_breve> <Greek_alpha>                               : "ᾰ"   U1FB0 # GREEK SMALL LETTER ALPHA WITH VRACHY
<dead_macron> <Greek_alpha>                              : "ᾱ"   U1FB1 # GREEK SMALL LETTER ALPHA WITH MACRON
<dead_grave> <dead_cedilla> <Greek_alpha>                : "ᾲ"   U1FB2 # GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_grave> <Greek_alpha>                : "ᾲ"   U1FB2 # GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
<dead_cedilla> <Greek_alpha>                             : "ᾳ"   U1FB3 # GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
<dead_acute> <dead_cedilla> <Greek_alpha>                : "ᾴ"   U1FB4 # GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_acute> <Greek_alpha>                : "ᾴ"   U1FB4 # GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
<dead_tilde> <Greek_alpha>                               : "ᾶ"   U1FB6 # GREEK SMALL LETTER ALPHA WITH PERISPOMENI
<dead_tilde> <dead_cedilla> <Greek_alpha>                : "ᾷ"   U1FB7 # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_tilde> <Greek_alpha>                : "ᾷ"   U1FB7 # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
<dead_grave> <dead_cedilla> <Greek_eta>                  : "ῂ"   U1FC2 # GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_grave> <Greek_eta>                  : "ῂ"   U1FC2 # GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
<dead_cedilla> <Greek_eta>                               : "ῃ"   U1FC3 # GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
<dead_acute> <dead_cedilla> <Greek_eta>                  : "ῄ"   U1FC4 # GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_acute> <Greek_eta>                  : "ῄ"   U1FC4 # GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
<dead_tilde> <Greek_eta>                                 : "ῆ"   U1FC6 # GREEK SMALL LETTER ETA WITH PERISPOMENI
<dead_tilde> <dead_cedilla> <Greek_eta>                  : "ῇ"   U1FC7 # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_tilde> <Greek_eta>                  : "ῇ"   U1FC7 # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
<dead_breve> <Greek_iota>                                : "ῐ"   U1FD0 # GREEK SMALL LETTER IOTA WITH VRACHY
<dead_macron> <Greek_iota>                               : "ῑ"   U1FD1 # GREEK SMALL LETTER IOTA WITH MACRON
<dead_diaeresis> <dead_grave> <Greek_iota>               : "ῒ"   U1FD2 # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
<dead_grave> <dead_diaeresis> <Greek_iota>               : "ῒ"   U1FD2 # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
<dead_tilde> <Greek_iota>                                : "ῖ"   U1FD6 # GREEK SMALL LETTER IOTA WITH PERISPOMENI
<dead_diaeresis> <dead_tilde> <Greek_iota>               : "ῗ"   U1FD7 # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
<dead_tilde> <dead_diaeresis> <Greek_iota>               : "ῗ"   U1FD7 # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
<dead_breve> <Greek_upsilon>                             : "ῠ"   U1FE0 # GREEK SMALL LETTER UPSILON WITH VRACHY
<dead_macron> <Greek_upsilon>                            : "ῡ"   U1FE1 # GREEK SMALL LETTER UPSILON WITH MACRON
<dead_diaeresis> <dead_grave> <Greek_upsilon>            : "ῢ"   U1FE2 # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
<dead_grave> <dead_diaeresis> <Greek_upsilon>            : "ῢ"   U1FE2 # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
<dead_psili> <Greek_rho>                                 : "ῤ"   U1FE4 # GREEK SMALL LETTER RHO WITH PSILI
<dead_dasia> <Greek_rho>                                 : "ῥ"   U1FE5 # GREEK SMALL LETTER RHO WITH DASIA
<dead_tilde> <Greek_upsilon>                             : "ῦ"   U1FE6 # GREEK SMALL LETTER UPSILON WITH PERISPOMENI
<dead_diaeresis> <dead_tilde> <Greek_upsilon>            : "ῧ"   U1FE7 # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
<dead_tilde> <dead_diaeresis> <Greek_upsilon>            : "ῧ"   U1FE7 # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
<dead_grave> <dead_cedilla> <Greek_omega>                : "ῲ"   U1FF2 # GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_grave> <Greek_omega>                : "ῲ"   U1FF2 # GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
<dead_cedilla> <Greek_omega>                             : "ῳ"   U1FF3 # GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
<dead_acute> <dead_cedilla> <Greek_omega>                : "ῴ"   U1FF4 # GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
<dead_cedilla> <dead_acute> <Greek_omega>                : "ῴ"   U1FF4 # GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
<dead_tilde> <Greek_omega>                               : "ῶ"   U1FF6 # GREEK SMALL LETTER OMEGA WITH PERISPOMENI
<dead_tilde> <dead_cedilla> <Greek_omega>                : "ῷ"   U1FF7 # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
<dead_cedilla> <dead_tilde> <Greek_omega>                : "ῷ"   U1FF7 # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI

<dead_psili> <Multi_key> <g> <A>                                        : "Ἀ"   U1F08 # GREEK CAPITAL LETTER ALPHA WITH PSILI
<dead_psili> <Multi_key> <G> <A>                                        : "Ἀ"   U1F08 # GREEK CAPITAL LETTER ALPHA WITH PSILI
<dead_dasia> <Multi_key> <g> <A>                                        : "Ἁ"   U1F09 # GREEK CAPITAL LETTER ALPHA WITH DASIA
<dead_dasia> <Multi_key> <G> <A>                                        : "Ἁ"   U1F09 # GREEK CAPITAL LETTER ALPHA WITH DASIA
<dead_psili> <dead_grave> <Multi_key> <g> <A>                           : "Ἂ"   U1F0A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA
<dead_psili> <dead_grave> <Multi_key> <G> <A>                           : "Ἂ"   U1F0A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Multi_key> <G> <A>                           : "Ἂ"   U1F0A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <g> <A>                           : "Ἃ"   U1F0B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <G> <A>                           : "Ἃ"   U1F0B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Multi_key> <G> <A>                           : "Ἃ"   U1F0B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Multi_key> <g> <A>                           : "Ἄ"   U1F0C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA
<dead_psili> <dead_acute> <Multi_key> <G> <A>                           : "Ἄ"   U1F0C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Multi_key> <G> <A>                           : "Ἄ"   U1F0C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <g> <A>                           : "Ἅ"   U1F0D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <G> <A>                           : "Ἅ"   U1F0D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Multi_key> <G> <A>                           : "Ἅ"   U1F0D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA
<dead_psili> <dead_tilde> <Multi_key> <g> <A>                           : "Ἆ"   U1F0E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI
<dead_psili> <dead_tilde> <Multi_key> <G> <A>                           : "Ἆ"   U1F0E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI
<dead_tilde> <dead_psili> <Multi_key> <G> <A>                           : "Ἆ"   U1F0E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI
<dead_dasia> <dead_tilde> <Multi_key> <g> <A>                           : "Ἇ"   U1F0F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI
<dead_dasia> <dead_tilde> <Multi_key> <G> <A>                           : "Ἇ"   U1F0F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Multi_key> <G> <A>                           : "Ἇ"   U1F0F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI
<dead_psili> <Multi_key> <g> <E>                                        : "Ἐ"   U1F18 # GREEK CAPITAL LETTER EPSILON WITH PSILI
<dead_psili> <Multi_key> <G> <E>                                        : "Ἐ"   U1F18 # GREEK CAPITAL LETTER EPSILON WITH PSILI
<dead_dasia> <Multi_key> <g> <E>                                        : "Ἑ"   U1F19 # GREEK CAPITAL LETTER EPSILON WITH DASIA
<dead_dasia> <Multi_key> <G> <E>                                        : "Ἑ"   U1F19 # GREEK CAPITAL LETTER EPSILON WITH DASIA
<dead_psili> <dead_grave> <Multi_key> <g> <E>                           : "Ἒ"   U1F1A # GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA
<dead_psili> <dead_grave> <Multi_key> <G> <E>                           : "Ἒ"   U1F1A # GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Multi_key> <G> <E>                           : "Ἒ"   U1F1A # GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <g> <E>                           : "Ἓ"   U1F1B # GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <G> <E>                           : "Ἓ"   U1F1B # GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Multi_key> <G> <E>                           : "Ἓ"   U1F1B # GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Multi_key> <g> <E>                           : "Ἔ"   U1F1C # GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA
<dead_psili> <dead_acute> <Multi_key> <G> <E>                           : "Ἔ"   U1F1C # GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Multi_key> <G> <E>                           : "Ἔ"   U1F1C # GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <g> <E>                           : "Ἕ"   U1F1D # GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <G> <E>                           : "Ἕ"   U1F1D # GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Multi_key> <G> <E>                           : "Ἕ"   U1F1D # GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
<dead_psili> <Multi_key> <g> <H>                                        : "Ἠ"   U1F28 # GREEK CAPITAL LETTER ETA WITH PSILI
<dead_psili> <Multi_key> <G> <H>                                        : "Ἠ"   U1F28 # GREEK CAPITAL LETTER ETA WITH PSILI
<dead_dasia> <Multi_key> <g> <H>                                        : "Ἡ"   U1F29 # GREEK CAPITAL LETTER ETA WITH DASIA
<dead_dasia> <Multi_key> <G> <H>                                        : "Ἡ"   U1F29 # GREEK CAPITAL LETTER ETA WITH DASIA
<dead_psili> <dead_grave> <Multi_key> <g> <H>                           : "Ἢ"   U1F2A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
<dead_psili> <dead_grave> <Multi_key> <G> <H>                           : "Ἢ"   U1F2A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Multi_key> <G> <H>                           : "Ἢ"   U1F2A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <g> <H>                           : "Ἣ"   U1F2B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <G> <H>                           : "Ἣ"   U1F2B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Multi_key> <G> <H>                           : "Ἣ"   U1F2B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Multi_key> <g> <H>                           : "Ἤ"   U1F2C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
<dead_psili> <dead_acute> <Multi_key> <G> <H>                           : "Ἤ"   U1F2C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Multi_key> <G> <H>                           : "Ἤ"   U1F2C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <g> <H>                           : "Ἥ"   U1F2D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <G> <H>                           : "Ἥ"   U1F2D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Multi_key> <G> <H>                           : "Ἥ"   U1F2D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
<dead_psili> <dead_tilde> <Multi_key> <g> <H>                           : "Ἦ"   U1F2E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
<dead_psili> <dead_tilde> <Multi_key> <G> <H>                           : "Ἦ"   U1F2E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
<dead_tilde> <dead_psili> <Multi_key> <G> <H>                           : "Ἦ"   U1F2E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
<dead_dasia> <dead_tilde> <Multi_key> <g> <H>                           : "Ἧ"   U1F2F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
<dead_dasia> <dead_tilde> <Multi_key> <G> <H>                           : "Ἧ"   U1F2F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Multi_key> <G> <H>                           : "Ἧ"   U1F2F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
<dead_psili> <Multi_key> <g> <Adiaeresis>                               : "Ἠ"   U1F28 # GREEK CAPITAL LETTER ETA WITH PSILI
<dead_psili> <Multi_key> <G> <Adiaeresis>                               : "Ἠ"   U1F28 # GREEK CAPITAL LETTER ETA WITH PSILI
<dead_dasia> <Multi_key> <g> <Adiaeresis>                               : "Ἡ"   U1F29 # GREEK CAPITAL LETTER ETA WITH DASIA
<dead_dasia> <Multi_key> <G> <Adiaeresis>                               : "Ἡ"   U1F29 # GREEK CAPITAL LETTER ETA WITH DASIA
<dead_psili> <dead_grave> <Multi_key> <g> <Adiaeresis>                  : "Ἢ"   U1F2A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
<dead_psili> <dead_grave> <Multi_key> <G> <Adiaeresis>                  : "Ἢ"   U1F2A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Multi_key> <G> <Adiaeresis>                  : "Ἢ"   U1F2A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <g> <Adiaeresis>                  : "Ἣ"   U1F2B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <G> <Adiaeresis>                  : "Ἣ"   U1F2B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Multi_key> <G> <Adiaeresis>                  : "Ἣ"   U1F2B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Multi_key> <g> <Adiaeresis>                  : "Ἤ"   U1F2C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
<dead_psili> <dead_acute> <Multi_key> <G> <Adiaeresis>                  : "Ἤ"   U1F2C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Multi_key> <G> <Adiaeresis>                  : "Ἤ"   U1F2C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <g> <Adiaeresis>                  : "Ἥ"   U1F2D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <G> <Adiaeresis>                  : "Ἥ"   U1F2D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Multi_key> <G> <Adiaeresis>                  : "Ἥ"   U1F2D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
<dead_psili> <dead_tilde> <Multi_key> <g> <Adiaeresis>                  : "Ἦ"   U1F2E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
<dead_psili> <dead_tilde> <Multi_key> <G> <Adiaeresis>                  : "Ἦ"   U1F2E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
<dead_tilde> <dead_psili> <Multi_key> <G> <Adiaeresis>                  : "Ἦ"   U1F2E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
<dead_dasia> <dead_tilde> <Multi_key> <g> <Adiaeresis>                  : "Ἧ"   U1F2F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
<dead_dasia> <dead_tilde> <Multi_key> <G> <Adiaeresis>                  : "Ἧ"   U1F2F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Multi_key> <G> <Adiaeresis>                  : "Ἧ"   U1F2F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
<dead_psili> <Multi_key> <g> <I>                                        : "Ἰ"   U1F38 # GREEK CAPITAL LETTER IOTA WITH PSILI
<dead_psili> <Multi_key> <G> <I>                                        : "Ἰ"   U1F38 # GREEK CAPITAL LETTER IOTA WITH PSILI
<dead_dasia> <Multi_key> <g> <I>                                        : "Ἱ"   U1F39 # GREEK CAPITAL LETTER IOTA WITH DASIA
<dead_dasia> <Multi_key> <G> <I>                                        : "Ἱ"   U1F39 # GREEK CAPITAL LETTER IOTA WITH DASIA
<dead_psili> <dead_grave> <Multi_key> <g> <I>                           : "Ἲ"   U1F3A # GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA
<dead_psili> <dead_grave> <Multi_key> <G> <I>                           : "Ἲ"   U1F3A # GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Multi_key> <G> <I>                           : "Ἲ"   U1F3A # GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <g> <I>                           : "Ἳ"   U1F3B # GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <G> <I>                           : "Ἳ"   U1F3B # GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Multi_key> <G> <I>                           : "Ἳ"   U1F3B # GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Multi_key> <g> <I>                           : "Ἴ"   U1F3C # GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA
<dead_psili> <dead_acute> <Multi_key> <G> <I>                           : "Ἴ"   U1F3C # GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Multi_key> <G> <I>                           : "Ἴ"   U1F3C # GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <g> <I>                           : "Ἵ"   U1F3D # GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <G> <I>                           : "Ἵ"   U1F3D # GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Multi_key> <G> <I>                           : "Ἵ"   U1F3D # GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA
<dead_psili> <dead_tilde> <Multi_key> <g> <I>                           : "Ἶ"   U1F3E # GREEK CAPITAL LETTER IOTA WITH PSILI AND PERISPOMENI
<dead_psili> <dead_tilde> <Multi_key> <G> <I>                           : "Ἶ"   U1F3E # GREEK CAPITAL LETTER IOTA WITH PSILI AND PERISPOMENI
<dead_tilde> <dead_psili> <Multi_key> <G> <I>                           : "Ἶ"   U1F3E # GREEK CAPITAL LETTER IOTA WITH PSILI AND PERISPOMENI
<dead_dasia> <dead_tilde> <Multi_key> <g> <I>                           : "Ἷ"   U1F3F # GREEK CAPITAL LETTER IOTA WITH DASIA AND PERISPOMENI
<dead_dasia> <dead_tilde> <Multi_key> <G> <I>                           : "Ἷ"   U1F3F # GREEK CAPITAL LETTER IOTA WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Multi_key> <G> <I>                           : "Ἷ"   U1F3F # GREEK CAPITAL LETTER IOTA WITH DASIA AND PERISPOMENI
<dead_psili> <Multi_key> <g> <O>                                        : "Ὀ"   U1F48 # GREEK CAPITAL LETTER OMICRON WITH PSILI
<dead_psili> <Multi_key> <G> <O>                                        : "Ὀ"   U1F48 # GREEK CAPITAL LETTER OMICRON WITH PSILI
<dead_dasia> <Multi_key> <g> <O>                                        : "Ὁ"   U1F49 # GREEK CAPITAL LETTER OMICRON WITH DASIA
<dead_dasia> <Multi_key> <G> <O>                                        : "Ὁ"   U1F49 # GREEK CAPITAL LETTER OMICRON WITH DASIA
<dead_psili> <dead_grave> <Multi_key> <g> <O>                           : "Ὂ"   U1F4A # GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA
<dead_psili> <dead_grave> <Multi_key> <G> <O>                           : "Ὂ"   U1F4A # GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Multi_key> <G> <O>                           : "Ὂ"   U1F4A # GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <g> <O>                           : "Ὃ"   U1F4B # GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <G> <O>                           : "Ὃ"   U1F4B # GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Multi_key> <G> <O>                           : "Ὃ"   U1F4B # GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Multi_key> <g> <O>                           : "Ὄ"   U1F4C # GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA
<dead_psili> <dead_acute> <Multi_key> <G> <O>                           : "Ὄ"   U1F4C # GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Multi_key> <G> <O>                           : "Ὄ"   U1F4C # GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <g> <O>                           : "Ὅ"   U1F4D # GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <G> <O>                           : "Ὅ"   U1F4D # GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Multi_key> <G> <O>                           : "Ὅ"   U1F4D # GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
<dead_dasia> <Multi_key> <g> <Y>                                        : "Ὑ"   U1F59 # GREEK CAPITAL LETTER UPSILON WITH DASIA
<dead_dasia> <Multi_key> <G> <Y>                                        : "Ὑ"   U1F59 # GREEK CAPITAL LETTER UPSILON WITH DASIA
<dead_dasia> <dead_grave> <Multi_key> <g> <Y>                           : "Ὓ"   U1F5B # GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
<dead_dasia> <dead_grave> <Multi_key> <G> <Y>                           : "Ὓ"   U1F5B # GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Multi_key> <G> <Y>                           : "Ὓ"   U1F5B # GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
<dead_dasia> <dead_acute> <Multi_key> <g> <Y>                           : "Ὕ"   U1F5D # GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
<dead_dasia> <dead_acute> <Multi_key> <G> <Y>                           : "Ὕ"   U1F5D # GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Multi_key> <G> <Y>                           : "Ὕ"   U1F5D # GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
<dead_dasia> <dead_tilde> <Multi_key> <g> <Y>                           : "Ὗ"   U1F5F # GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI
<dead_dasia> <dead_tilde> <Multi_key> <G> <Y>                           : "Ὗ"   U1F5F # GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Multi_key> <G> <Y>                           : "Ὗ"   U1F5F # GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI
<dead_psili> <Greek_OMEGA>                                              : "Ὠ"   U1F68 # GREEK CAPITAL LETTER OMEGA WITH PSILI
<dead_dasia> <Greek_OMEGA>                                              : "Ὡ"   U1F69 # GREEK CAPITAL LETTER OMEGA WITH DASIA
<dead_psili> <dead_grave> <Greek_OMEGA>                                 : "Ὢ"   U1F6A # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA
<dead_grave> <dead_psili> <Greek_OMEGA>                                 : "Ὢ"   U1F6A # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA
<dead_dasia> <dead_grave> <Greek_OMEGA>                                 : "Ὣ"   U1F6B # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA
<dead_grave> <dead_dasia> <Greek_OMEGA>                                 : "Ὣ"   U1F6B # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA
<dead_psili> <dead_acute> <Greek_OMEGA>                                 : "Ὤ"   U1F6C # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA
<dead_acute> <dead_psili> <Greek_OMEGA>                                 : "Ὤ"   U1F6C # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA
<dead_dasia> <dead_acute> <Greek_OMEGA>                                 : "Ὥ"   U1F6D # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA
<dead_acute> <dead_dasia> <Greek_OMEGA>                                 : "Ὥ"   U1F6D # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA
<dead_psili> <dead_tilde> <Greek_OMEGA>                                 : "Ὦ"   U1F6E # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI
<dead_tilde> <dead_psili> <Greek_OMEGA>                                 : "Ὦ"   U1F6E # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI
<dead_dasia> <dead_tilde> <Greek_OMEGA>                                 : "Ὧ"   U1F6F # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI
<dead_tilde> <dead_dasia> <Greek_OMEGA>                                 : "Ὧ"   U1F6F # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI
<dead_psili> <dead_cedilla> <Multi_key> <g> <A>                         : "ᾈ"   U1F88 # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <Multi_key> <G> <A>                         : "ᾈ"   U1F88 # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <Multi_key> <G> <A>                         : "ᾈ"   U1F88 # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <Multi_key> <g> <A>                         : "ᾉ"   U1F89 # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <Multi_key> <G> <A>                         : "ᾉ"   U1F89 # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <Multi_key> <G> <A>                         : "ᾉ"   U1F89 # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
<dead_psili> <dead_grave> <dead_cedilla> <Multi_key> <g> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_grave> <dead_cedilla> <Multi_key> <G> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_grave> <Multi_key> <g> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_grave> <Multi_key> <G> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_psili> <dead_cedilla> <Multi_key> <g> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_psili> <dead_cedilla> <Multi_key> <G> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_psili> <Multi_key> <g> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_psili> <Multi_key> <G> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_grave> <Multi_key> <g> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_grave> <Multi_key> <G> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_psili> <Multi_key> <g> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_psili> <Multi_key> <G> <A>            : "ᾊ"   U1F8A # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_grave> <dead_cedilla> <Multi_key> <g> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_grave> <dead_cedilla> <Multi_key> <G> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_grave> <Multi_key> <g> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_grave> <Multi_key> <G> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_dasia> <dead_cedilla> <Multi_key> <g> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_dasia> <dead_cedilla> <Multi_key> <G> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_dasia> <Multi_key> <g> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_dasia> <Multi_key> <G> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_grave> <Multi_key> <g> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_grave> <Multi_key> <G> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_dasia> <Multi_key> <g> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_dasia> <Multi_key> <G> <A>            : "ᾋ"   U1F8B # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_acute> <dead_cedilla> <Multi_key> <g> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_acute> <dead_cedilla> <Multi_key> <G> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_acute> <Multi_key> <g> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_acute> <Multi_key> <G> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_psili> <dead_cedilla> <Multi_key> <g> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_psili> <dead_cedilla> <Multi_key> <G> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_psili> <Multi_key> <g> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_psili> <Multi_key> <G> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_acute> <Multi_key> <g> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_acute> <Multi_key> <G> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_psili> <Multi_key> <g> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_psili> <Multi_key> <G> <A>            : "ᾌ"   U1F8C # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_acute> <dead_cedilla> <Multi_key> <g> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_acute> <dead_cedilla> <Multi_key> <G> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_acute> <Multi_key> <g> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_acute> <Multi_key> <G> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_dasia> <dead_cedilla> <Multi_key> <g> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_dasia> <dead_cedilla> <Multi_key> <G> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_dasia> <Multi_key> <g> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_dasia> <Multi_key> <G> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_acute> <Multi_key> <g> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_acute> <Multi_key> <G> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_dasia> <Multi_key> <g> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_dasia> <Multi_key> <G> <A>            : "ᾍ"   U1F8D # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_tilde> <dead_cedilla> <Multi_key> <g> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_tilde> <dead_cedilla> <Multi_key> <G> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_tilde> <Multi_key> <g> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_tilde> <Multi_key> <G> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_psili> <dead_cedilla> <Multi_key> <g> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_psili> <dead_cedilla> <Multi_key> <G> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_psili> <Multi_key> <g> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_psili> <Multi_key> <G> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_tilde> <Multi_key> <g> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_tilde> <Multi_key> <G> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_psili> <Multi_key> <g> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_psili> <Multi_key> <G> <A>            : "ᾎ"   U1F8E # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_tilde> <dead_cedilla> <Multi_key> <g> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_tilde> <dead_cedilla> <Multi_key> <G> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_tilde> <Multi_key> <g> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_tilde> <Multi_key> <G> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_dasia> <dead_cedilla> <Multi_key> <g> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_dasia> <dead_cedilla> <Multi_key> <G> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_dasia> <Multi_key> <g> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_dasia> <Multi_key> <G> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_tilde> <Multi_key> <g> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_tilde> <Multi_key> <G> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_dasia> <Multi_key> <g> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_dasia> <Multi_key> <G> <A>            : "ᾏ"   U1F8F # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <Multi_key> <g> <H>                         : "ᾘ"   U1F98 # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <Multi_key> <G> <H>                         : "ᾘ"   U1F98 # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <Multi_key> <G> <H>                         : "ᾘ"   U1F98 # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <Multi_key> <g> <H>                         : "ᾙ"   U1F99 # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <Multi_key> <G> <H>                         : "ᾙ"   U1F99 # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <Multi_key> <G> <H>                         : "ᾙ"   U1F99 # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
<dead_psili> <dead_grave> <dead_cedilla> <Multi_key> <g> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_grave> <dead_cedilla> <Multi_key> <G> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_grave> <Multi_key> <g> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_grave> <Multi_key> <G> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_psili> <dead_cedilla> <Multi_key> <g> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_psili> <dead_cedilla> <Multi_key> <G> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_psili> <Multi_key> <g> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_psili> <Multi_key> <G> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_grave> <Multi_key> <g> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_grave> <Multi_key> <G> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_psili> <Multi_key> <g> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_psili> <Multi_key> <G> <H>            : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_grave> <dead_cedilla> <Multi_key> <g> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_grave> <dead_cedilla> <Multi_key> <G> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_grave> <Multi_key> <g> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_grave> <Multi_key> <G> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_dasia> <dead_cedilla> <Multi_key> <g> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_dasia> <dead_cedilla> <Multi_key> <G> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_dasia> <Multi_key> <g> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_dasia> <Multi_key> <G> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_grave> <Multi_key> <g> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_grave> <Multi_key> <G> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_dasia> <Multi_key> <g> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_dasia> <Multi_key> <G> <H>            : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_acute> <dead_cedilla> <Multi_key> <g> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_acute> <dead_cedilla> <Multi_key> <G> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_acute> <Multi_key> <g> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_acute> <Multi_key> <G> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_psili> <dead_cedilla> <Multi_key> <g> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_psili> <dead_cedilla> <Multi_key> <G> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_psili> <Multi_key> <g> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_psili> <Multi_key> <G> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_acute> <Multi_key> <g> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_acute> <Multi_key> <G> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_psili> <Multi_key> <g> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_psili> <Multi_key> <G> <H>            : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_acute> <dead_cedilla> <Multi_key> <g> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_acute> <dead_cedilla> <Multi_key> <G> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_acute> <Multi_key> <g> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_acute> <Multi_key> <G> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_dasia> <dead_cedilla> <Multi_key> <g> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_dasia> <dead_cedilla> <Multi_key> <G> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_dasia> <Multi_key> <g> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_dasia> <Multi_key> <G> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_acute> <Multi_key> <g> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_acute> <Multi_key> <G> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_dasia> <Multi_key> <g> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_dasia> <Multi_key> <G> <H>            : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_tilde> <dead_cedilla> <Multi_key> <g> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_tilde> <dead_cedilla> <Multi_key> <G> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_tilde> <Multi_key> <g> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_tilde> <Multi_key> <G> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_psili> <dead_cedilla> <Multi_key> <g> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_psili> <dead_cedilla> <Multi_key> <G> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_psili> <Multi_key> <g> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_psili> <Multi_key> <G> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_tilde> <Multi_key> <g> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_tilde> <Multi_key> <G> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_psili> <Multi_key> <g> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_psili> <Multi_key> <G> <H>            : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_tilde> <dead_cedilla> <Multi_key> <g> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_tilde> <dead_cedilla> <Multi_key> <G> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_tilde> <Multi_key> <g> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_tilde> <Multi_key> <G> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_dasia> <dead_cedilla> <Multi_key> <g> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_dasia> <dead_cedilla> <Multi_key> <G> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_dasia> <Multi_key> <g> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_dasia> <Multi_key> <G> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_tilde> <Multi_key> <g> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_tilde> <Multi_key> <G> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_dasia> <Multi_key> <g> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_dasia> <Multi_key> <G> <H>            : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <Multi_key> <g> <Adiaeresis>                : "ᾘ"   U1F98 # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <Multi_key> <G> <Adiaeresis>                : "ᾘ"   U1F98 # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <Multi_key> <G> <Adiaeresis>                : "ᾘ"   U1F98 # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <Multi_key> <g> <Adiaeresis>                : "ᾙ"   U1F99 # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <Multi_key> <G> <Adiaeresis>                : "ᾙ"   U1F99 # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <Multi_key> <G> <Adiaeresis>                : "ᾙ"   U1F99 # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
<dead_psili> <dead_grave> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_grave> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_grave> <Multi_key> <g> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_grave> <Multi_key> <G> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_psili> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_psili> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_psili> <Multi_key> <g> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_psili> <Multi_key> <G> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_grave> <Multi_key> <g> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_grave> <Multi_key> <G> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_psili> <Multi_key> <g> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_psili> <Multi_key> <G> <Adiaeresis>   : "ᾚ"   U1F9A # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_grave> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_grave> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_grave> <Multi_key> <g> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_grave> <Multi_key> <G> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_dasia> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_dasia> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_dasia> <Multi_key> <g> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_dasia> <Multi_key> <G> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_grave> <Multi_key> <g> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_grave> <Multi_key> <G> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_dasia> <Multi_key> <g> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_dasia> <Multi_key> <G> <Adiaeresis>   : "ᾛ"   U1F9B # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_acute> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_acute> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_acute> <Multi_key> <g> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_acute> <Multi_key> <G> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_psili> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_psili> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_psili> <Multi_key> <g> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_psili> <Multi_key> <G> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_acute> <Multi_key> <g> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_acute> <Multi_key> <G> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_psili> <Multi_key> <g> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_psili> <Multi_key> <G> <Adiaeresis>   : "ᾜ"   U1F9C # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_acute> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_acute> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_acute> <Multi_key> <g> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_acute> <Multi_key> <G> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_dasia> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_dasia> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_dasia> <Multi_key> <g> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_dasia> <Multi_key> <G> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_acute> <Multi_key> <g> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_acute> <Multi_key> <G> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_dasia> <Multi_key> <g> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_dasia> <Multi_key> <G> <Adiaeresis>   : "ᾝ"   U1F9D # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_tilde> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_tilde> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_tilde> <Multi_key> <g> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_tilde> <Multi_key> <G> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_psili> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_psili> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_psili> <Multi_key> <g> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_psili> <Multi_key> <G> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_tilde> <Multi_key> <g> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_tilde> <Multi_key> <G> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_psili> <Multi_key> <g> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_psili> <Multi_key> <G> <Adiaeresis>   : "ᾞ"   U1F9E # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_tilde> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_tilde> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_tilde> <Multi_key> <g> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_tilde> <Multi_key> <G> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_dasia> <dead_cedilla> <Multi_key> <g> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_dasia> <dead_cedilla> <Multi_key> <G> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_dasia> <Multi_key> <g> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_dasia> <Multi_key> <G> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_tilde> <Multi_key> <g> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_tilde> <Multi_key> <G> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_dasia> <Multi_key> <g> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_dasia> <Multi_key> <G> <Adiaeresis>   : "ᾟ"   U1F9F # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <Greek_OMEGA>                               : "ᾨ"   U1FA8 # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <Greek_OMEGA>                               : "ᾨ"   U1FA8 # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <Greek_OMEGA>                               : "ᾩ"   U1FA9 # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <Greek_OMEGA>                               : "ᾩ"   U1FA9 # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
<dead_psili> <dead_grave> <dead_cedilla> <Greek_OMEGA>                  : "ᾪ"   U1FAA # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_grave> <Greek_OMEGA>                  : "ᾪ"   U1FAA # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_psili> <dead_cedilla> <Greek_OMEGA>                  : "ᾪ"   U1FAA # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_psili> <Greek_OMEGA>                  : "ᾪ"   U1FAA # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_grave> <Greek_OMEGA>                  : "ᾪ"   U1FAA # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_psili> <Greek_OMEGA>                  : "ᾪ"   U1FAA # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_grave> <dead_cedilla> <Greek_OMEGA>                  : "ᾫ"   U1FAB # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_grave> <Greek_OMEGA>                  : "ᾫ"   U1FAB # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_dasia> <dead_cedilla> <Greek_OMEGA>                  : "ᾫ"   U1FAB # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_grave> <dead_cedilla> <dead_dasia> <Greek_OMEGA>                  : "ᾫ"   U1FAB # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_grave> <Greek_OMEGA>                  : "ᾫ"   U1FAB # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_grave> <dead_dasia> <Greek_OMEGA>                  : "ᾫ"   U1FAB # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
<dead_psili> <dead_acute> <dead_cedilla> <Greek_OMEGA>                  : "ᾬ"   U1FAC # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_acute> <Greek_OMEGA>                  : "ᾬ"   U1FAC # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_psili> <dead_cedilla> <Greek_OMEGA>                  : "ᾬ"   U1FAC # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_psili> <Greek_OMEGA>                  : "ᾬ"   U1FAC # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_acute> <Greek_OMEGA>                  : "ᾬ"   U1FAC # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_psili> <Greek_OMEGA>                  : "ᾬ"   U1FAC # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_acute> <dead_cedilla> <Greek_OMEGA>                  : "ᾭ"   U1FAD # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_acute> <Greek_OMEGA>                  : "ᾭ"   U1FAD # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_dasia> <dead_cedilla> <Greek_OMEGA>                  : "ᾭ"   U1FAD # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_acute> <dead_cedilla> <dead_dasia> <Greek_OMEGA>                  : "ᾭ"   U1FAD # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_acute> <Greek_OMEGA>                  : "ᾭ"   U1FAD # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_cedilla> <dead_acute> <dead_dasia> <Greek_OMEGA>                  : "ᾭ"   U1FAD # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
<dead_psili> <dead_tilde> <dead_cedilla> <Greek_OMEGA>                  : "ᾮ"   U1FAE # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_psili> <dead_cedilla> <dead_tilde> <Greek_OMEGA>                  : "ᾮ"   U1FAE # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_psili> <dead_cedilla> <Greek_OMEGA>                  : "ᾮ"   U1FAE # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_psili> <Greek_OMEGA>                  : "ᾮ"   U1FAE # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_psili> <dead_tilde> <Greek_OMEGA>                  : "ᾮ"   U1FAE # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_psili> <Greek_OMEGA>                  : "ᾮ"   U1FAE # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_tilde> <dead_cedilla> <Greek_OMEGA>                  : "ᾯ"   U1FAF # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_dasia> <dead_cedilla> <dead_tilde> <Greek_OMEGA>                  : "ᾯ"   U1FAF # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_dasia> <dead_cedilla> <Greek_OMEGA>                  : "ᾯ"   U1FAF # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_tilde> <dead_cedilla> <dead_dasia> <Greek_OMEGA>                  : "ᾯ"   U1FAF # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_dasia> <dead_tilde> <Greek_OMEGA>                  : "ᾯ"   U1FAF # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_cedilla> <dead_tilde> <dead_dasia> <Greek_OMEGA>                  : "ᾯ"   U1FAF # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
<dead_breve> <Multi_key> <g> <A>                                        : "Ᾰ"   U1FB8 # GREEK CAPITAL LETTER ALPHA WITH VRACHY
<dead_breve> <Multi_key> <G> <A>                                        : "Ᾰ"   U1FB8 # GREEK CAPITAL LETTER ALPHA WITH VRACHY
<dead_macron> <Multi_key> <g> <A>                                       : "Ᾱ"   U1FB9 # GREEK CAPITAL LETTER ALPHA WITH MACRON
<dead_macron> <Multi_key> <G> <A>                                       : "Ᾱ"   U1FB9 # GREEK CAPITAL LETTER ALPHA WITH MACRON
<dead_grave> <Multi_key> <g> <A>                                        : "Ὰ"   U1FBA # GREEK CAPITAL LETTER ALPHA WITH VARIA
<dead_grave> <Multi_key> <G> <A>                                        : "Ὰ"   U1FBA # GREEK CAPITAL LETTER ALPHA WITH VARIA
<dead_cedilla> <Multi_key> <g> <A>                                      : "ᾼ"   U1FBC # GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
<dead_cedilla> <Multi_key> <G> <A>                                      : "ᾼ"   U1FBC # GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
<dead_grave> <Multi_key> <g> <E>                                        : "Ὲ"   U1FC8 # GREEK CAPITAL LETTER EPSILON WITH VARIA
<dead_grave> <Multi_key> <G> <E>                                        : "Ὲ"   U1FC8 # GREEK CAPITAL LETTER EPSILON WITH VARIA
<dead_grave> <Multi_key> <g> <H>                                        : "Ὴ"   U1FCA # GREEK CAPITAL LETTER ETA WITH VARIA
<dead_grave> <Multi_key> <G> <H>                                        : "Ὴ"   U1FCA # GREEK CAPITAL LETTER ETA WITH VARIA
<dead_cedilla> <Multi_key> <g> <H>                                      : "ῌ"   U1FCC # GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
<dead_cedilla> <Multi_key> <G> <H>                                      : "ῌ"   U1FCC # GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
<dead_grave> <Multi_key> <g> <Adiaeresis>                               : "Ὴ"   U1FCA # GREEK CAPITAL LETTER ETA WITH VARIA
<dead_grave> <Multi_key> <G> <Adiaeresis>                               : "Ὴ"   U1FCA # GREEK CAPITAL LETTER ETA WITH VARIA
<dead_cedilla> <Multi_key> <g> <Adiaeresis>                             : "ῌ"   U1FCC # GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
<dead_cedilla> <Multi_key> <G> <Adiaeresis>                             : "ῌ"   U1FCC # GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
<dead_breve> <Multi_key> <g> <I>                                        : "Ῐ"   U1FD8 # GREEK CAPITAL LETTER IOTA WITH VRACHY
<dead_breve> <Multi_key> <G> <I>                                        : "Ῐ"   U1FD8 # GREEK CAPITAL LETTER IOTA WITH VRACHY
<dead_macron> <Multi_key> <g> <I>                                       : "Ῑ"   U1FD9 # GREEK CAPITAL LETTER IOTA WITH MACRON
<dead_macron> <Multi_key> <G> <I>                                       : "Ῑ"   U1FD9 # GREEK CAPITAL LETTER IOTA WITH MACRON
<dead_grave> <Multi_key> <g> <I>                                        : "Ὶ"   U1FDA # GREEK CAPITAL LETTER IOTA WITH VARIA
<dead_grave> <Multi_key> <G> <I>                                        : "Ὶ"   U1FDA # GREEK CAPITAL LETTER IOTA WITH VARIA
<dead_breve> <Multi_key> <g> <Y>                                        : "Ῠ"   U1FE8 # GREEK CAPITAL LETTER UPSILON WITH VRACHY
<dead_breve> <Multi_key> <G> <Y>                                        : "Ῠ"   U1FE8 # GREEK CAPITAL LETTER UPSILON WITH VRACHY
<dead_macron> <Multi_key> <g> <Y>                                       : "Ῡ"   U1FE9 # GREEK CAPITAL LETTER UPSILON WITH MACRON
<dead_macron> <Multi_key> <G> <Y>                                       : "Ῡ"   U1FE9 # GREEK CAPITAL LETTER UPSILON WITH MACRON
<dead_grave> <Multi_key> <g> <Y>                                        : "Ὺ"   U1FEA # GREEK CAPITAL LETTER UPSILON WITH VARIA
<dead_grave> <Multi_key> <G> <Y>                                        : "Ὺ"   U1FEA # GREEK CAPITAL LETTER UPSILON WITH VARIA
<dead_acute> <U02DE> <Multi_key> <g> <Y>                                : "ϓ"   U03D3 # GREEK UPSILON WITH ACUTE AND HOOK SYMBOL
<dead_acute> <U02DE> <Multi_key> <G> <Y>                                : "ϓ"   U03D3 # GREEK UPSILON WITH ACUTE AND HOOK SYMBOL
<dead_dasia> <Multi_key> <g> <Greek_RHO>                                : "Ῥ"   U1FEC # GREEK CAPITAL LETTER RHO WITH DASIA
<dead_dasia> <Multi_key> <G> <Greek_RHO>                                : "Ῥ"   U1FEC # GREEK CAPITAL LETTER RHO WITH DASIA
<dead_grave> <Multi_key> <g> <O>                                        : "Ὸ"   U1FF8 # GREEK CAPITAL LETTER OMICRON WITH VARIA
<dead_grave> <Multi_key> <G> <O>                                        : "Ὸ"   U1FF8 # GREEK CAPITAL LETTER OMICRON WITH VARIA
<dead_grave> <Greek_OMEGA>                                              : "Ὼ"   U1FFA # GREEK CAPITAL LETTER OMEGA WITH VARIA
<dead_cedilla> <Greek_OMEGA>                                            : "ῼ"   U1FFC # GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
<dead_diaeresis> <Multi_key> <g> <I>                                    : "Ϊ"   U03AA # GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
<dead_diaeresis> <Multi_key> <G> <I>                                    : "Ϊ"   U03AA # GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
<dead_diaeresis> <Multi_key> <g> <Y>                                    : "Ϋ"   U03AB # GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
<dead_diaeresis> <Multi_key> <G> <Y>                                    : "Ϋ"   U03AB # GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
# usage discouraged:
#<dead_diaeresis> <U02DE> <Multi_key> <g> <Y>                       : "ϔ"   U03D4 # GREEK UPSILON WITH DIAERESIS AND HOOK SYMBOL
#<dead_diaeresis> <U02DE> <Multi_key> <G> <Y>                       : "ϔ"   U03D4 # GREEK UPSILON WITH DIAERESIS AND HOOK SYMBOL

# greek letters with tonos instead of oxia (if wanted)
<dead_acute> <Greek_alpha>                                         : "ά"   U03AC # GREEK SMALL LETTER ALPHA WITH TONOS
<dead_acute> <Greek_epsilon>                                       : "έ"   U03AD # GREEK SMALL LETTER EPSILON WITH TONOS
<dead_acute> <Greek_eta>                                           : "ή"   U03AE # GREEK SMALL LETTER ETA WITH TONOS
<dead_acute> <Greek_iota>                                          : "ί"   U03AF # GREEK SMALL LETTER IOTA WITH TONOS
<dead_acute> <Greek_omicron>                                       : "ό"   U03CC # GREEK SMALL LETTER OMICRON WITH TONOS
<dead_acute> <Greek_upsilon>                                       : "ύ"   U03CD # GREEK SMALL LETTER UPSILON WITH TONOS
<dead_acute> <Greek_omega>                                         : "ώ"   U03CE # GREEK SMALL LETTER OMEGA WITH TONOS
<dead_acute> <Multi_key> <g> <A>                                   : "Ά"   U0386 # GREEK CAPITAL LETTER ALPHA WITH TONOS
<dead_acute> <Multi_key> <G> <A>                                   : "Ά"   U0386 # GREEK CAPITAL LETTER ALPHA WITH TONOS
<dead_acute> <Multi_key> <g> <E>                                   : "Έ"   U0388 # GREEK CAPITAL LETTER EPSILON WITH TONOS
<dead_acute> <Multi_key> <G> <E>                                   : "Έ"   U0388 # GREEK CAPITAL LETTER EPSILON WITH TONOS
<dead_acute> <Multi_key> <g> <H>                                   : "Ή"   U0389 # GREEK CAPITAL LETTER ETA WITH TONOS
<dead_acute> <Multi_key> <G> <H>                                   : "Ή"   U0389 # GREEK CAPITAL LETTER ETA WITH TONOS
<dead_acute> <Multi_key> <g> <Adiaeresis>                          : "Ή"   U0389 # GREEK CAPITAL LETTER ETA WITH TONOS
<dead_acute> <Multi_key> <G> <Adiaeresis>                          : "Ή"   U0389 # GREEK CAPITAL LETTER ETA WITH TONOS
<dead_acute> <Multi_key> <g> <I>                                   : "Ί"   U038A # GREEK CAPITAL LETTER IOTA WITH TONOS
<dead_acute> <Multi_key> <G> <I>                                   : "Ί"   U038A # GREEK CAPITAL LETTER IOTA WITH TONOS
<dead_acute> <Multi_key> <g> <O>                                   : "Ό"   U038C # GREEK CAPITAL LETTER OMICRON WITH TONOS
<dead_acute> <Multi_key> <G> <O>                                   : "Ό"   U038C # GREEK CAPITAL LETTER OMICRON WITH TONOS
<dead_acute> <Multi_key> <g> <Y>                                   : "Ύ"   U038E # GREEK CAPITAL LETTER UPSILON WITH TONOS
<dead_acute> <Multi_key> <G> <Y>                                   : "Ύ"   U038E # GREEK CAPITAL LETTER UPSILON WITH TONOS
<dead_acute> <Greek_OMEGA>                                         : "Ώ"   U038F # GREEK CAPITAL LETTER OMEGA WITH TONOS

# additional greek symbols
# Greek ampersand symbols
<U02DE> <Greek_kappa>                                                : "ϗ"   U03D7 # GREEK KAI SYMBOL
<U02DE> <U03F0>                                                      : "ϗ"   U03D7 # GREEK KAI SYMBOL
<U02DE> <Greek_KAPPA>                                                : "Ϗ"   U03CF # GREEK CAPITAL KAI SYMBOL
<U02DE> <Multi_key> <g> <K>                                          : "Ϗ"   U03CF # GREEK CAPITAL KAI SYMBOL
<U02DE> <Multi_key> <G> <K>                                          : "Ϗ"   U03CF # GREEK CAPITAL KAI SYMBOL

# ligatures and variants
<Multi_key> <Greek_SIGMA> <Greek_tau>                                : "Ϛ"   U03DA # GREEK LETTER STIGMA
<Multi_key> <Greek_SIGMA> <Greek_TAU>                                : "Ϛ"   U03DA # GREEK LETTER STIGMA
<Multi_key> <Greek_sigma> <Greek_tau>                                : "ϛ"   U03DB # GREEK SMALL LETTER STIGMA
<Multi_key> <Greek_beta> <Greek_beta>                                : "ϐ"   U03D0 # GREEK BETA SYMBOL
<Multi_key> <Greek_omega> <Greek_pi>                                 : "ϖ"   U03D6 # GREEK PI SYMBOL
<Multi_key> <Greek_pi> <Greek_omega>                                 : "ϖ"   U03D6 # GREEK PI SYMBOL
<dead_stroke> <Greek_rho>                                            : "ϼ"   U03FC # GREEK RHO WITH STROKE SYMBOL
<U21BB> <U03F5>                                                      : "϶"   U03F6 # GREEK REVERSED LUNATE EPSILON SYMBOL

# archaic greek, not supported at the moment: Ϟϟ Ϡϡ Ϻϻ Ͱͱ
<Multi_key> <g> <F>                                                  : "Ϝ"   U03DC # GREEK LETTER DIGAMMA
<Multi_key> <G> <F>                                                  : "Ϝ"   U03DC # GREEK LETTER DIGAMMA
<Multi_key> <g> <f>                                                  : "ϝ"   U03DD # GREEK SMALL LETTER DIGAMMA
<Multi_key> <g> <Q>                                                  : "Ϙ"   U03D8 # GREEK LETTER ARCHAIC KOPPA
<Multi_key> <G> <Q>                                                  : "Ϙ"   U03D8 # GREEK LETTER ARCHAIC KOPPA
<Multi_key> <g> <q>                                                  : "ϙ"   U03D9 # GREEK SMALL LETTER ARCHAIC KOPPA
<Multi_key> <g> <j>                                                  : "ϳ"   U03F3 # GREEK LETTER YOT
<Multi_key> <g> <C>                                                  : "Ϲ"   U03F9 # GREEK CAPITAL LUNATE SIGMA SYMBOL
<Multi_key> <G> <C>                                                  : "Ϲ"   U03F9 # GREEK CAPITAL LUNATE SIGMA SYMBOL
<Multi_key> <g> <c>                                                  : "ϲ"   U03F2 # GREEK LUNATE SIGMA SYMBOL

# direct versions not available as letters are not on keyboard
<U21BB> <U03F2>                                                      : "ͻ"   U037B # GREEK SMALL REVERSED LUNATE SIGMA SYMBOL
<U21BB> <Multi_key> <g> <c>                                          : "ͻ"   U037B # GREEK SMALL REVERSED LUNATE SIGMA SYMBOL
<dead_abovedot> <U03F2>                                              : "ͼ"   U037C # GREEK SMALL DOTTED LUNATE SIGMA SYMBOL
<dead_abovedot> <Multi_key> <g> <c>                                  : "ͼ"   U037C # GREEK SMALL DOTTED LUNATE SIGMA SYMBOL
<dead_abovedot> <U21BB> <U03F2>                                      : "ͽ"   U037D # GREEK SMALL REVERSED DOTTED LUNATE SIGMA SYMBOL
<dead_abovedot> <U21BB> <Multi_key> <g> <c>                          : "ͽ"   U037D # GREEK SMALL REVERSED DOTTED LUNATE SIGMA SYMBOL
<U21BB> <U03F9>                                                      : "Ͻ"   U03FD # GREEK CAPITAL REVERSED LUNATE SIGMA SYMBOL
<U21BB> <Multi_key> <g> <C>                                          : "Ͻ"   U03FD # GREEK CAPITAL REVERSED LUNATE SIGMA SYMBOL
<U21BB> <Multi_key> <G> <C>                                          : "Ͻ"   U03FD # GREEK CAPITAL REVERSED LUNATE SIGMA SYMBOL
<dead_abovedot> <U03F9>                                              : "Ͼ"   U03FE # GREEK CAPITAL DOTTED LUNATE SIGMA SYMBOL
<dead_abovedot> <Multi_key> <g> <C>                                  : "Ͼ"   U03FE # GREEK CAPITAL DOTTED LUNATE SIGMA SYMBOL
<dead_abovedot> <Multi_key> <G> <C>                                  : "Ͼ"   U03FE # GREEK CAPITAL DOTTED LUNATE SIGMA SYMBOL
<dead_abovedot> <U21BB> <U03F9>                                      : "Ͽ"   U03FF # GREEK CAPITAL REVERSED DOTTED LUNATE SIGMA SYMBOL
<dead_abovedot> <U21BB> <Multi_key> <g> <C>                          : "Ͽ"   U03FF # GREEK CAPITAL REVERSED DOTTED LUNATE SIGMA SYMBOL
<dead_abovedot> <U21BB> <Multi_key> <G> <C>                          : "Ͽ"   U03FF # GREEK CAPITAL REVERSED DOTTED LUNATE SIGMA SYMBOL

# numeral sign turn
<U21BB> <U0374>                                                      : "͵"   U0375 # GREEK LOWER NUMERAL SIGN

# older/alternative version by ♫··
<Multi_key> <U03DE> <U03DE>                                          : "Ϙ"   U03D8 # GREEK LETTER ARCHAIC KOPPA
<Multi_key> <U03DF> <U03DF>                                          : "ϙ"   U03D9 # GREEK SMALL LETTER ARCHAIC KOPPA
<Multi_key> <U03DC> <U03DC>                                          : "Ͷ"   U0376 # GREEK CAPITAL LETTER PAMPHYLIAN DIGAMMA
<Multi_key> <U03DD> <U03DD>                                          : "ͷ"   U0377 # GREEK SMALL LETTER PAMPHYLIAN DIGAMMA
<Multi_key> <U03E0> <U03E0>                                          : "Ͳ"   U0372 # GREEK CAPITAL LETTER ARCHAIC SAMPI
<Multi_key> <U03E1> <U03E1>                                          : "ͳ"   U0373 # GREEK SMALL LETTER ARCHAIC SAMPI

# End of additional Definitions (greek letters) by Neo keyboard layout
