#configinfo IPA (int. phonetic alphabet) und weitere Sprachen ([neːo] Ɱɐ ẻ ʔ)

# IPA-Compose by aleχ, 2009, CC-BY-SA DE 3.
# turned letters (most African and IPA usage)
<U21BB> <a>                                       : "ɐ" U0250 # LATIN SMALL LETTER TURNED A
<U21BB> <C>                                       : "Ɔ" U0186 # LATIN CAPITAL LETTER OPEN O
<U21BB> <c>                                       : "ɔ" U0254 # LATIN SMALL LETTER OPEN O
<U21BB> <e>                                       : "ɘ" U0258 # LATIN SMALL LETTER REVERSED E
<U21BB> <h>                                       : "ɥ" U0265 # LATIN SMALL LETTER TURNED H
<U21BB> <m>                                       : "ɯ" U026F # LATIN SMALL LETTER TURNED M
<U21BB> <R>                                       : "ʁ" U0281 # LATIN LETTER SMALL CAPITAL INVERTED R
<U21BB> <r>                                       : "ɹ" U0279 # LATIN SMALL LETTER TURNED R
<U21BB> <Multi_key> <r> <r>                       : "ɺ" U027A # LATIN SMALL LETTER TURNED R WITH LONG LEG
<U21BB> <S>                                       : "Ƨ" U01A7 # LATIN CAPITAL LETTER TONE TWO
<U21BB> <V>                                       : "Ʌ" U0245 # LATIN CAPITAL LETTER TURNED V
<U21BB> <v>                                       : "ʌ" U028C # LATIN SMALL LETTER TURNED V
<U21BB> <w>                                       : "ʍ" U028D # LATIN SMALL LETTER TURNED W
<U21BB> <y>                                       : "ʎ" U028E # LATIN SMALL LETTER TURNED Y
<U21BB> <Greek_lambda>                            : "ʎ" U028E # LATIN SMALL LETTER TURNED Y
<U21BB> <3>                                       : "Ɛ" U0190 # LATIN CAPITAL LETTER OPEN E
<U21BB> <Greek_alpha>                             : "ɒ" U0252 # LATIN SMALL LETTER TURNED ALPHA
<U21BB> <Multi_key> <a> <a>                       : "ɒ" U0252 # LATIN SMALL LETTER TURNED ALPHA
<U21BB> <Multi_key> <Greek_alpha> <Greek_alpha>   : "ɒ" U0252 # LATIN SMALL LETTER TURNED ALPHA
<U21BB> <Greek_OMEGA>                             : "Ʊ" U01B1 # LATIN CAPITAL LETTER UPSILON
<U21BB> <Multi_key> <h> <n>                       : "ɰ" U0270 # LATIN SMALL LETTER TURNED M WITH LONG LEG
# Pan-nigeran reversed e with ‚n‘ for ‚nigerian‘, to be discussed, but up to now no alternative has been found (Ǝ ≠ ∃, ǝ ≠ ə)
<Multi_key> <N> <E>                               : "Ǝ" U018E # LATIN CAPITAL LETTER REVERSED E
<Multi_key> <n> <e>                               : "ǝ" U01DD # LATIN SMALL LETTER TURNED E

# letters with hook (most African and IPA usage)
<U02DE> <B>                                       : "Ɓ" U0181 # LATIN CAPITAL LETTER B WITH HOOK
<U02DE> <b>                                       : "ɓ" U0253 # LATIN SMALL LETTER B WITH HOOK
<U02DE> <C>                                       : "Ƈ" U0187 # LATIN CAPITAL LETTER C WITH HOOK
<U02DE> <c>                                       : "ƈ" U0188 # LATIN SMALL LETTER C WITH HOOK
<U02DE> <D>                                       : "Ɗ" U018A # LATIN CAPITAL LETTER D WITH HOOK
<U02DE> <d>                                       : "ɗ" U0257 # LATIN SMALL LETTER D WITH HOOK
<U02DE> <F>                                       : "Ƒ" U0191 # LATIN CAPITAL LETTER F WITH HOOK
<U02DE> <f>                                       : "ƒ" U0192 # LATIN SMALL LETTER F WITH HOOK
<U02DE> <Multi_key> <G> <G>                       : "ʛ" U029B # LATIN LETTER SMALL CAPITAL G WITH HOOK
<U02DE> <G>                                       : "Ɠ" U0193 # LATIN CAPITAL LETTER G WITH HOOK
<U02DE> <g>                                       : "ɠ" U0260 # LATIN SMALL LETTER G WITH HOOK
<U02DE> <h>                                       : "ɦ" U0266 # LATIN SMALL LETTER H WITH HOOK
<U02DE> <I>                                       : "Ɩ" U0196 # LATIN CAPITAL LETTER IOTA
<U02DE> <i>                                       : "ɩ" U0269 # LATIN SMALL LETTER IOTA
<U02DE> <j>                                       : "ʝ" U029D # LATIN SMALL LETTER J WITH CROSSED-TAIL
<U02DE> <K>                                       : "Ƙ" U0198 # LATIN CAPITAL LETTER K WITH HOOK
<U02DE> <k>                                       : "ƙ" U0199 # LATIN SMALL LETTER K WITH HOOK
<U02DE> <l>                                       : "ɬ" U026C # LATIN SMALL LETTER L WITH BELT
<U02DE> <M>                                       : "Ɱ" U2C6E # LATIN CAPITAL LETTER M WITH HOOK
<U02DE> <m>                                       : "ɱ" U0271 # LATIN SMALL LETTER M WITH HOOK
<U02DE> <N>                                       : "Ŋ" U014A # LATIN CAPITAL LETTER ENG
<U02DE> <n>                                       : "ŋ" U014B # LATIN SMALL LETTER ENG
<U02DE> <P>                                       : "Ƥ" U01A4 # LATIN CAPITAL LETTER P WITH HOOK
<U02DE> <p>                                       : "ƥ" U01A5 # LATIN SMALL LETTER P WITH HOOK
<U02DE> <R>                                       : "Ɽ" U2C64 # LATIN CAPITAL LETTER R WITH TAIL
<U02DE> <r>                                       : "ɽ" U027D # LATIN SMALL LETTER R WITH TAIL
<U02DE> <s>                                       : "ʂ" U0282 # LATIN SMALL LETTER S WITH HOOK
<U02DE> <T>                                       : "Ƭ" U01AC # LATIN CAPITAL LETTER T WITH HOOK
<U02DE> <t>                                       : "ƭ" U01AD # LATIN SMALL LETTER T WITH HOOK
<U02DE> <v>                                       : "ⱱ" U2C71 # LATIN SMALL LETTER V WITH RIGHT HOOK
<U02DE> <W>                                       : "Ⱳ" U2C72 # LATIN CAPITAL LETTER W WITH HOOK
<U02DE> <w>                                       : "ⱳ" U2C73 # LATIN SMALL LETTER W WITH HOOK
<U02DE> <X>                                       : "Ɣ" U0194 # LATIN CAPITAL LETTER GAMMA
<U02DE> <x>                                       : "ɣ" U0263 # LATIN SMALL LETTER GAMMA
<Multi_key> <Greek_gamma> <Greek_gamma>           : "ɣ" U0263 # LATIN SMALL LETTER GAMMA
<U02DE> <Y>                                       : "Ƴ" U01B3 # LATIN CAPITAL LETTER Y WITH HOOK
<U02DE> <y>                                       : "ƴ" U01B4 # LATIN SMALL LETTER Y WITH HOOK
<U02DE> <z>                                       : "ʐ" U0290 # LATIN SMALL LETTER Z WITH RETROFLEX HOOK
<U02DE> <Multi_key> <e> <e>                       : "ɚ" U025A # LATIN SMALL LETTER SCHWA WITH HOOK
<U02DE> <3>                                       : "ɝ" U025D # LATIN SMALL LETTER REVERSED OPEN E WITH HOOK
<Multi_key> <V> <parenright>                      : "Ʋ" U01B2 # LATIN CAPITAL LETTER V WITH HOOK
<Multi_key> <v> <parenright>                      : "ʋ" U028B # LATIN SMALL LETTER V WITH HOOK
<Multi_key> <n> <l>                               : "ɳ" U0273 # LATIN SMALL LETTER N WITH RETROFLEX HOOK
<Multi_key> <l> <l>                               : "ɭ" U026D # LATIN SMALL LETTER L WITH RETROFLEX HOOK
<Multi_key> <T> <l>                               : "Ʈ" U01AE # LATIN CAPITAL LETTER T WITH RETROFLEX HOOK
<Multi_key> <T> <L>                               : "Ʈ" U01AE # LATIN CAPITAL LETTER T WITH RETROFLEX HOOK
<Multi_key> <t> <l>                               : "ʈ" U0288 # LATIN SMALL LETTER T WITH RETROFLEX HOOK
<U02DE> <U21BB> <r>                               : "ɻ" U027B # LATIN SMALL LETTER TURNED R WITH HOOK
<Multi_key> <j> <N>                               : "Ɲ" U019D # LATIN CAPITAL LETTER N WITH LEFT HOOK
<Multi_key> <J> <N>                               : "Ɲ" U019D # LATIN CAPITAL LETTER N WITH LEFT HOOK
<Multi_key> <j> <n>                               : "ɲ" U0272 # LATIN SMALL LETTER N WITH LEFT HOOK
<Multi_key> <D> <l>                               : "Ɖ" U0189 # LATIN CAPITAL LETTER AFRICAN D
<Multi_key> <D> <L>                               : "Ɖ" U0189 # LATIN CAPITAL LETTER AFRICAN D
<Multi_key> <d> <l>                               : "ɖ" U0256 # LATIN SMALL LETTER D WITH TAIL
<Multi_key> <U02DE> <h> <j>                       : "ɧ" U0267 # LATIN SMALL LETTER HENG WITH HOOK
<Multi_key> <U02DE> <h> <g>                       : "ɧ" U0267 # LATIN SMALL LETTER HENG WITH HOOK

# additional stroke letters (only ʉ, ɵ, ɟ and ʄ are IPA) 
<dead_stroke> <A>                                 : "Ⱥ" U023A # LATIN CAPITAL LETTER A WITH STROKE
<Multi_key> <slash> <A>                           : "Ⱥ" U023A # LATIN CAPITAL LETTER A WITH STROKE
<Multi_key> <KP_Divide> <A>                       : "Ⱥ" U023A # LATIN CAPITAL LETTER A WITH STROKE
<dead_stroke> <a>                                 : "ⱥ" U2C65 # LATIN SMALL LETTER A WITH STROKE
<Multi_key> <slash> <a>                           : "ⱥ" U2C65 # LATIN SMALL LETTER A WITH STROKE
<Multi_key> <KP_Divide> <a>                       : "ⱥ" U2C65 # LATIN SMALL LETTER A WITH STROKE
<dead_stroke> <B>                                 : "Ƀ" U0243 # LATIN CAPITAL LETTER B WITH STROKE
<Multi_key> <minus> <B>                           : "Ƀ" U0243 # LATIN CAPITAL LETTER B WITH STROKE
<dead_stroke> <C>                                 : "Ȼ" U023B # LATIN CAPITAL LETTER C WITH STROKE
<Multi_key> <slash> <C>                           : "Ȼ" U023B # LATIN CAPITAL LETTER C WITH STROKE
<Multi_key> <KP_Divide> <C>                       : "Ȼ" U023B # LATIN CAPITAL LETTER C WITH STROKE
<dead_stroke> <c>                                 : "ȼ" U023C # LATIN SMALL LETTER C WITH STROKE
<Multi_key> <slash> <c>                           : "ȼ" U023C # LATIN SMALL LETTER C WITH STROKE
<Multi_key> <KP_Divide> <c>                       : "ȼ" U023C # LATIN SMALL LETTER C WITH STROKE
<dead_stroke> <E>                                 : "Ɇ" U0246 # LATIN CAPITAL LETTER E WITH STROKE
<Multi_key> <slash> <E>                           : "Ɇ" U0246 # LATIN CAPITAL LETTER E WITH STROKE
<Multi_key> <KP_Divide> <E>                       : "Ɇ" U0246 # LATIN CAPITAL LETTER E WITH STROKE
<dead_stroke> <e>                                 : "ɇ" U0247 # LATIN SMALL LETTER E WITH STROKE
<Multi_key> <slash> <e>                           : "ɇ" U0247 # LATIN SMALL LETTER E WITH STROKE
<Multi_key> <KP_Divide> <e>                       : "ɇ" U0247 # LATIN SMALL LETTER E WITH STROKE
<dead_stroke> <I>                                 : "Ɨ" U0197 # LATIN CAPITAL LETTER I WITH STROKE
<Multi_key> <minus> <I>                           : "Ɨ" U0197 # LATIN CAPITAL LETTER I WITH STROKE
<dead_stroke> <Multi_key> <I> <I>                 : "ᵻ" U1D7B # LATIN SMALL CAPITAL LETTER I WITH STROKE
<Multi_key> <minus> <J>                           : "Ɉ" U0248 # LATIN CAPITAL LETTER J WITH STROKE
<Multi_key> <minus> <j>                           : "ɉ" U0249 # LATIN SMALL LETTER J WITH STROKE
<dead_stroke> <J>                                 : "ɟ" U025F # LATIN SMALL LETTER DOTLESS J WITH STROKE
<dead_stroke> <j>                                 : "ɟ" U025F # LATIN SMALL LETTER DOTLESS J WITH STROKE
<dead_stroke> <dead_abovedot> <j>                 : "ɟ" U025F # LATIN SMALL LETTER DOTLESS J WITH STROKE
<U02DE> <dead_stroke> <J>                         : "ʄ" U0284 # LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK
<Multi_key> <j> <f>                               : "ʄ" U0284 # LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK
# Collides with standard compose £ and ₤:
<Multi_key> <minus> <L>                           : "Ƚ" U023D # LATIN CAPITAL LETTER L WITH BAR
<Multi_key> <minus> <l>                           : "ƚ" U019A # LATIN SMALL LETTER L WITH BAR
<Multi_key> <equal> <L>                          : "Ⱡ" U2C60 # LATIN CAPITAL LETTER L WITH DOUBLE BAR
<Multi_key> <equal> <l>                          : "ⱡ" U2C61 # LATIN SMALL LETTER L WITH DOUBLE BAR
<Multi_key> <minus> <o>                           : "ɵ" U0275 # LATIN SMALL LETTER BARRED O
<Multi_key> <minus> <O>                           : "Ɵ" U019F # LATIN CAPITAL LETTER O WITH MIDDLE TILDE
<dead_stroke> <P>                                 : "Ᵽ" U2C63 # LATIN CAPITAL LETTER P WITH STROKE
<Multi_key> <minus> <P>                           : "Ᵽ" U2C63 # LATIN CAPITAL LETTER P WITH STROKE
<dead_stroke> <p>                                 : "ᵽ" U1D7D # LATIN SMALL LETTER P WITH STROKE
<Multi_key> <minus> <p>                           : "ᵽ" U1D7D # LATIN SMALL LETTER P WITH STROKE
<dead_stroke> <R>                                 : "Ɍ" U024C # LATIN CAPITAL LETTER R WITH STROKE
<Multi_key> <minus> <R>                           : "Ɍ" U024C # LATIN CAPITAL LETTER R WITH STROKE
<dead_stroke> <r>                                 : "ɍ" U024D # LATIN SMALL LETTER R WITH STROKE
<Multi_key> <minus> <r>                           : "ɍ" U024D # LATIN SMALL LETTER R WITH STROKE
<Multi_key> <slash> <T>                           : "Ⱦ" U023E # LATIN CAPITAL LETTER T WITH DIAGONAL STROKE
<Multi_key> <KP_Divide> <T>                       : "Ⱦ" U023E # LATIN CAPITAL LETTER T WITH DIAGONAL STROKE
<Multi_key> <slash> <t>                           : "ⱦ" U2C66 # LATIN SMALL LETTER T WITH DIAGONAL STROKE
<Multi_key> <KP_Divide> <t>                       : "ⱦ" U2C66 # LATIN SMALL LETTER T WITH DIAGONAL STROKE
<dead_stroke> <u>                                 : "ʉ" U0289 # LATIN SMALL LETTER U BAR
<Multi_key> <minus> <u>                           : "ʉ" U0289 # LATIN SMALL LETTER U BAR
<dead_stroke> <U>                                 : "Ʉ" U0244 # LATIN CAPITAL LETTER U BAR
<Multi_key> <minus> <U>                           : "Ʉ" U0244 # LATIN CAPITAL LETTER U BAR
<dead_stroke> <Y>                                 : "Ɏ" U024E # LATIN CAPITAL LETTER Y WITH STROKE
<Multi_key> <minus> <Y>                           : "Ɏ" U024E # LATIN CAPITAL LETTER Y WITH STROKE
<dead_stroke> <y>                                 : "ɏ" U024F # LATIN SMALL LETTER Y WITH STROKE
<Multi_key> <minus> <y>                           : "ɏ" U024F # LATIN SMALL LETTER Y WITH STROKE
<dead_stroke> <Greek_lambda>                      : "ƛ" U019B # LATIN SMALL LETTER LAMBDA WITH STROKE
<Multi_key> <slash> <Greek_lambda>                : "ƛ" U019B # LATIN SMALL LETTER LAMBDA WITH STROKE
<Multi_key> <KP_Divide> <Greek_lambda>            : "ƛ" U019B # LATIN SMALL LETTER LAMBDA WITH STROKE
# It is undecided whether they should be included:
#<dead_stroke> <2>                                 : "ƻ" U01BB # LATIN LETTER TWO WITH STROKE
<Multi_key> <minus> <2>                           : "ƻ" U01BB # LATIN LETTER TWO WITH STROKE
<dead_stroke> <Greek_iota>                        : "ᵼ" U1D7C # LATIN SMALL LETTER IOTA WITH STROKE
<Multi_key> <minus> <Greek_iota>                  : "ᵼ" U1D7C # LATIN SMALL LETTER IOTA WITH STROKE
<dead_stroke> <Greek_upsilon>                     : "ᵿ" U1D7F # LATIN SMALL LETTER UPSILON WITH STROKE
<Multi_key> <minus> <Greek_upsilon>               : "ᵿ" U1D7F # LATIN SMALL LETTER UPSILON WITH STROKE
<dead_stroke> <Multi_key> <U> <U>                 : "ᵾ" U1D7E # LATIN SMALL CAPITAL LETTER U WITH STROKE

# IPA, african and other languages
<Multi_key> <l> <z>                               : "ɮ" U026E # LATIN SMALL LETTER LEZH
<Multi_key> <Z> <H>                               : "Ʒ" U01B7 # LATIN CAPITAL LETTER EZH
<Multi_key> <Z> <Z>                               : "Ʒ" U01B7 # LATIN CAPITAL LETTER EZH
<dead_caron> <Multi_key> <Z> <H>                  : "Ǯ" U01EE # LATIN CAPITAL LETTER EZH WITH CARON
<dead_caron> <Multi_key> <z> <h>                  : "ǯ" U01EF # LATIN SMALL LETTER EZH WITH CARON
<U21BB> <Multi_key> <Z> <Z>                       : "Ƹ" U01B8 # LATIN CAPITAL LETTER EZH REVERSED
<U21BB> <Multi_key> <z> <z>                       : "ƹ" U01B9 # LATIN SMALL LETTER EZH REVERSED
<Multi_key> <S> <H>                               : "Ʃ" U01A9 # LATIN CAPITAL LETTER ESH
<Multi_key> <s> <h>                               : "ʃ" U0283 # LATIN SMALL LETTER ESH

# capital letters (IPA)
<Multi_key> <B> <B>                               : "ʙ" U0299 # LATIN LETTER SMALL CAPITAL B
<Multi_key> <G> <G>                               : "ɢ" U0262 # LATIN LETTER SMALL CAPITAL G
<Multi_key> <H> <H>                               : "ʜ" U029C # LATIN LETTER SMALL CAPITAL H
<Multi_key> <I> <I>                               : "ɪ" U026A # LATIN LETTER SMALL CAPITAL I
<Multi_key> <L> <L>                               : "ʟ" U029F # LATIN LETTER SMALL CAPITAL L
<Multi_key> <N> <N>                               : "ɴ" U0274 # LATIN LETTER SMALL CAPITAL N
<Multi_key> <R> <R>                               : "ʀ" U0280 # LATIN LETTER SMALL CAPITAL R
<Multi_key> <Y> <Y>                               : "ʏ" U028F # LATIN LETTER SMALL CAPITAL Y
<Multi_key> <O> <O> <E>                           : "ɶ" U0276 # LATIN LETTER SMALL CAPITAL OE

# latin greek letters (IPA and African)
<Multi_key> <C> <bar>                             : "Ɑ" U2C6D # LATIN CAPITAL LETTER ALPHA
<Multi_key> <a> <a>                               : "ɑ" U0251 # LATIN SMALL LETTER ALPHA
<Multi_key> <Greek_alpha> <Greek_alpha>           : "ɑ" U0251 # LATIN SMALL LETTER ALPHA
<Multi_key> <Greek_epsilon> <Greek_epsilon>       : "ɛ" U025B # LATIN SMALL LETTER OPEN E
<Multi_key> <Greek_phi> <Greek_phi>               : "ɸ" U0278 # LATIN SMALL LETTER PHI
<Multi_key> <U03D5> <U03D5>                       : "ɸ" U0278 # LATIN SMALL LETTER PHI
<Multi_key> <Greek_upsilon> <Greek_upsilon>       : "ʊ" U028A # LATIN SMALL LETTER UPSILON
<Multi_key> <3> <3>                               : "ɜ" U025C # LATIN SMALL LETTER REVERSED OPEN E
<Multi_key> <KP_3> <KP_3>                         : "ɜ" U025C # LATIN SMALL LETTER REVERSED OPEN E

# letters with curl (IPA)
<dead_abovering> <c>                              : "ɕ" U0255 # LATIN SMALL LETTER C WITH CURL
<dead_abovering> <z>                              : "ʑ" U0291 # LATIN SMALL LETTER Z WITH CURL
# non-IPA sinologist
<dead_abovering> <d>                              : "ȡ" U0221 # LATIN SMALL LETTER D WITH CURL
<dead_abovering> <l>                              : "ȴ" U0234 # LATIN SMALL LETTER L WITH CURL
<dead_abovering> <n>                              : "ȵ" U0235 # LATIN SMALL LETTER N WITH CURL
<dead_abovering> <t>                              : "ȶ" U0236 # LATIN SMALL LETTER T WITH CURL

# other letters (IPA)
<Multi_key> <i> <question>                        : "ʔ" U0294 # LATIN LETTER GLOTTAL STOP
<dead_stroke> <Multi_key> <i> <question>          : "ʡ" U02A1 # LATIN LETTER GLOTTAL STOP WITH STROKE
<U21BB> <Multi_key> <i> <question>                : "ʕ" U0295 # LATIN LETTER PHARYNGEAL VOICED FRICATIVE
<dead_stroke> <U21BB> <question>                  : "ʢ" U02A2 # LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE
<dead_stroke> <U21BB> <Multi_key> <i> <question>  : "ʢ" U02A2 # LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE
<Multi_key> <g> <g>                               : "ɡ" U0261 # LATIN SMALL LETTER SCRIPT G
<U21BB> <Greek_tau>                               : "ɾ" U027E # LATIN SMALL LETTER R WITH FISHHOOK
<Multi_key> <r> <underscore>                      : "ɾ" U027E # LATIN SMALL LETTER R WITH FISHHOOK
<Multi_key> <r> <r>                               : "ɼ" U027C # LATIN SMALL LETTER R WITH LONG LEG
<Multi_key> <parenleft> <3> <space>               : "ɞ" U025E # LATIN SMALL LETTER CLOSED REVERSED OPEN E
<Multi_key> <parenleft> <KP_3> <space>            : "ɞ" U025E # LATIN SMALL LETTER CLOSED REVERSED OPEN E
<Multi_key> <x> <underscore>                      : "ɤ" U0264 # LATIN SMALL LETTER RAMS HORN

# IPA clicks
<Multi_key> <equal> <bar>                         : "ǂ" U01C2 # LATIN LETTER ALVEOLAR CLICK
<Multi_key> <KP_Equal> <bar>                      : "ǂ" U01C2 # LATIN LETTER ALVEOLAR CLICK
<Multi_key> <i> <bar> <space>                     : "ǀ" U01C0 # LATIN LETTER DENTAL CLICK
<Multi_key> <i> <bar> <bar>                       : "ǁ" U01C1 # LATIN LETTER LATERAL CLICK
<Multi_key> <i> <exclam>                          : "ǃ" U01C3 # LATIN LETTER RETROFLEX CLICK
<Multi_key> <0> <period>                          : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<Multi_key> <KP_0> <period>                       : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<Multi_key> <period> <0>                          : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<Multi_key> <period> <KP_0>                       : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<dead_abovedot> <0>                               : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<dead_abovedot> <KP_0>                            : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK

# modifiers (IPA)
<Multi_key> <colon> <colon>                       : "ː" U02D0 # MODIFIER LETTER TRIANGULAR COLON
<Multi_key> <periodcentered> <periodcentered>     : "ˑ" U02D1 # MODIFIER LETTER HALF TRIANGULAR COLON
<Multi_key> <apostrophe> <apostrophe>             : "ˈ" U02C8 # MODIFIER LETTER VERTICAL LINE
<Multi_key> <underscore> <apostrophe>             : "ˌ" U02CC # MODIFIER LETTER LOW VERTICAL LINE
<U21BB> <Multi_key> <apostrophe> <apostrophe>     : "ˌ" U02CC # MODIFIER LETTER LOW VERTICAL LINE
<U21BB> <parenright>                              : "‿" U203F # UNDERTIE
<U21BB> <parenleft>                               : "͡" U0361 # COMBINING DOUBLE INVERTED BREVE

# tone letters (t) and Standard Mandarin tones
<Multi_key> <t> <5>                               : "˥" U02E5 # MODIFIER LETTER EXTRA-HIGH TONE BAR
<Multi_key> <t> <4>                               : "˦" U02E6 # MODIFIER LETTER HIGH TONE BAR
<Multi_key> <t> <3>                               : "˧" U02E7 # MODIFIER LETTER MID TONE BAR
<Multi_key> <t> <2>                               : "˨" U02E8 # MODIFIER LETTER LOW TONE BAR
<Multi_key> <t> <1>                               : "˩" U02E9 # MODIFIER LETTER EXTRA-LOW TONE BAR
<Multi_key> <m> <1>                               : "˥˥"
<Multi_key> <m> <2>                               : "˧˥"
<Multi_key> <m> <3>                               : "˨˩˦"
<Multi_key> <m> <4>                               : "˥˩"
<dead_circumflex> <Multi_key> <bar> <asciicircum> : "ꜛ" UA71B # MODIFIER LETTER RAISED UP ARROW
<dead_circumflex> <Multi_key> <v> <bar>           : "ꜜ" UA71C # MODIFIER LETTER RAISED DOWN ARROW

# diakritics – work in progress
<dead_circumflex> <U21BB> <L>                     : "̚" U031A # COMBINING LEFT ANGLE ABOVE
<dead_circumflex> <multiply>                      : "̽" U033D # COMBINING X ABOVE
<Multi_key> <asciicircum> <multiply>              : "̽" U033D # COMBINING X ABOVE
<U21BB> <dead_abovering> <dead_abovering>         : "̥" U0325 # COMBINING RING BELOW
<Multi_key> <underscore> <dead_abovering>         : "̥" U0325 # COMBINING RING BELOW
<U21BB> <dead_diaeresis> <dead_diaeresis>         : "̤" U0324 # COMBINING DIAERESIS BELOW
<Multi_key> <underscore> <dead_diaeresis>         : "̤" U0324 # COMBINING DIAERESIS BELOW
<U21BB> <dead_tilde> <dead_tilde>                 : "̰" U0330 # COMBINING TILDE BELOW
<Multi_key> <underscore> <dead_tilde>             : "̰" U0330 # COMBINING TILDE BELOW
<Multi_key> <underscore> <dead_breve>             : "̯" U032F # COMBINING INVERTED BREVE BELOW
<Multi_key> <underscore> <dead_circumflex> <dead_circumflex> : "̭" U032D # COMBINING CIRCUMFLEX ACCENT BELOW
<Multi_key> <underscore> <dead_caron>             : "̬" U032C # COMBINING CARON BELOW
<Multi_key> <underscore> <m>                      : "̼" U033C # COMBINING SEAGULL BELOW
<Multi_key> <i> <plus>                            : "̟" U031F # COMBINING PLUS SIGN BELOW
<Multi_key> <i> <minus>                           : "̠" U0320 # COMBINING MINUS SIGN BELOW
<Multi_key> <underscore> <bar>                    : "̩" U0329 # COMBINING VERTICAL LINE BELOW
<Multi_key> <underscore> <dead_macron>            : "̱" U0331 # COMBINING MACRON BELOW
<Multi_key> <underscore> <U22A5>                  : "̝" U031D # COMBINING UP TACK BELOW
<Multi_key> <underscore> <U21BB> <U22A5>          : "̞" U031E # COMBINING DOWN TACK BELOW
<Multi_key> <underscore> <c>                      : "̜" U031C # COMBINING LEFT HALF RING BELOW
<Multi_key> <underscore> <U21BB> <c>              : "̹" U0339 # COMBINING RIGHT HALF RING BELOW
<Multi_key> <underscore> <U25A1>                  : "̻" U033B # COMBINING SQUARE BELOW
<Multi_key> <underscore> <U21BB> <bracketright>   : "̺" U033A # COMBINING INVERTED BRIDGE BELOW
<Multi_key> <underscore> <U21BB> <bracketleft>    : "̪" U032A # COMBINING BRIDGE BELOW
# Missing: U+0319 COMBINING RIGHT TACK BELOW, U+0318 COMBINING LEFT TACK BELOW, U+0334 COMBINING TILDE OVERLAY, 
# U+0351 COMBINING LEFT HALF RING ABOVE, U+0357 COMBINING RIGHT HALF RING ABOVE, U+0346 COMBINING BRIDGE ABOVE

# tone accents:
<Multi_key> <dead_macron> <dead_acute>            : "᷄" U1DC4 # COMBINING MACRON-ACUTE
<Multi_key> <dead_grave> <dead_macron>            : "᷅" U1DC5 # COMBINING GRAVE-MACRON
<Multi_key> <dead_acute> <dead_macron>            : "᷇" U1DC7 # COMBINING ACUTE-MACRON
<Multi_key> <dead_macron> <dead_grave>            : "᷆" U1DC6 # COMBINING MACRON-GRAVE
<Multi_key> <dead_grave> <dead_acute> <dead_grave>: "᷈" U1DC8 # COMBINING GRAVE-ACUTE-GRAVE
<Multi_key> <dead_acute> <dead_grave> <dead_acute>: "᷉" U1DC9 # COMBINING ACUTE-GRAVE-ACUTE

# superscript IPA letters
<dead_circumflex> <U02DE> <m>                     : "ᶬ" U1DAC # MODIFIER LETTER SMALL M WITH HOOK
<dead_circumflex> <Multi_key> <n> <l>             : "ᶯ" U1DAF # MODIFIER LETTER SMALL N WITH RETROFLEX HOOK
<dead_circumflex> <Multi_key> <j> <n>             : "ᶮ" U1DAE # MODIFIER LETTER SMALL N WITH LEFT HOOK
<dead_circumflex> <U02DE> <n>                     : "ᵑ" U1D51 # MODIFIER LETTER SMALL ENG
<dead_circumflex> <Multi_key> <n> <g>             : "ᵑ" U1D51 # MODIFIER LETTER SMALL ENG
<dead_circumflex> <Multi_key> <N> <N>             : "ᶰ" U1DB0 # MODIFIER LETTER SMALL CAPITAL N
<dead_circumflex> <dead_stroke> <j>               : "ᶡ" U1DA1 # MODIFIER LETTER SMALL DOTLESS J WITH STROKE
<dead_circumflex> <dead_stroke> <J>               : "ᶡ" U1DA1 # MODIFIER LETTER SMALL DOTLESS J WITH STROKE
<dead_circumflex> <Multi_key> <g> <g>             : "ᶢ" U1DA2 # MODIFIER LETTER SMALL SCRIPT G
<dead_circumflex> <question>                      : "ˀ" U02C0 # MODIFIER LETTER GLOTTAL STOP
<dead_circumflex> <U03D5>                         : "ᶲ" U1DB2 # MODIFIER LETTER SMALL PHI
<dead_circumflex> <Multi_key> <d> <h>             : "ᶞ" U1D9E # MODIFIER LETTER SMALL ETH
<dead_circumflex> <Multi_key> <s> <h>             : "ᶴ" U1DB4 # MODIFIER LETTER SMALL ESH
<dead_circumflex> <Multi_key> <z> <h>             : "ᶾ" U1DBE # MODIFIER LETTER SMALL EZH
<dead_circumflex> <Multi_key> <z> <z>             : "ᶾ" U1DBE # MODIFIER LETTER SMALL EZH
<dead_circumflex> <U02DE> <s>                     : "ᶳ" U1DB3 # MODIFIER LETTER SMALL S WITH HOOK
<dead_circumflex> <U02DE> <z>                     : "ᶼ" U1DBC # MODIFIER LETTER SMALL Z WITH RETROFLEX HOOK
<dead_circumflex> <U02DE> <j>                     : "ᶨ" U1DA8 # MODIFIER LETTER SMALL J WITH CROSSED-TAIL
<dead_circumflex> <U02DE> <x>                     : "ˠ" U02E0 # MODIFIER LETTER SMALL GAMMA
<dead_circumflex> <U21BB> <R>                     : "ʶ" U02B6 # MODIFIER LETTER SMALL CAPITAL INVERTED R
<dead_circumflex> <U21BB> <question>              : "ˁ" U02C1 # MODIFIER LETTER REVERSED GLOTTAL STOP
<dead_circumflex> <U02DE> <h>                     : "ʱ" U02B1 # MODIFIER LETTER SMALL H WITH HOOK
<dead_circumflex> <Multi_key> <v> <parenright>    : "ᶹ" U1DB9 # MODIFIER LETTER SMALL V WITH HOOK
<dead_circumflex> <U21BB> <r>                     : "ʴ" U02B4 # MODIFIER LETTER SMALL TURNED R
<dead_circumflex> <U02DE> <U21BB> <r>             : "ʵ" U02B5 # MODIFIER LETTER SMALL TURNED R WITH HOOK
<dead_circumflex> <U21BB> <Multi_key> <h> <n>     : "ᶭ" U1DAD # MODIFIER LETTER SMALL TURNED M WITH LONG LEG
<dead_circumflex> <Multi_key> <l> <l>             : "ᶩ" U1DA9 # MODIFIER LETTER SMALL L WITH RETROFLEX HOOK
<dead_circumflex> <Multi_key> <L> <L>             : "ᶫ" U1DAB # MODIFIER LETTER SMALL CAPITAL L
<dead_circumflex> <U21BB> <h>                     : "ᶣ" U1DA3 # MODIFIER LETTER SMALL TURNED H
<dead_circumflex> <dead_abovering> <c>            : "ᶝ" U1D9D # MODIFIER LETTER SMALL C WITH CURL
<dead_circumflex> <dead_abovering> <z>            : "ᶽ" U1DBD # MODIFIER LETTER SMALL Z WITH CURL
<dead_circumflex> <dead_stroke> <i>               : "ᶤ" U1DA4 # MODIFIER LETTER SMALL I WITH STROKE
<dead_circumflex> <Multi_key> <minus> <i>         : "ᶤ" U1DA4 # MODIFIER LETTER SMALL I WITH STROKE
<dead_circumflex> <dead_stroke> <u>               : "ᶶ" U1DB6 # MODIFIER LETTER SMALL U BAR
<dead_circumflex> <Multi_key> <minus> <u>         : "ᶶ" U1DB6 # MODIFIER LETTER SMALL U BAR
<dead_circumflex> <U21BB> <m>                     : "ᵚ" U1D5A # MODIFIER LETTER SMALL TURNED M
<dead_circumflex> <Multi_key> <I> <I>             : "ᶦ" U1DA6 # MODIFIER LETTER SMALL CAPITAL I
<dead_circumflex> <Greek_upsilon>                 : "ᶷ" U1DB7 # MODIFIER LETTER SMALL UPSILON
<dead_circumflex> <Multi_key> <minus> <o>         : "ᶱ" U1DB1 # MODIFIER LETTER SMALL BARRED O
<dead_circumflex> <Multi_key> <e> <e>             : "ᵊ" U1D4A # MODIFIER LETTER SMALL SCHWA
<dead_circumflex> <Greek_epsilon>                 : "ᵋ" U1D4B # MODIFIER LETTER SMALL OPEN E
<dead_circumflex> <Multi_key> <3> <3>             : "ᶟ" U1D9F # MODIFIER LETTER SMALL REVERSED OPEN E
<dead_circumflex> <U21BB> <v>                     : "ᶺ" U1DBA # MODIFIER LETTER SMALL TURNED V
<dead_circumflex> <U21BB> <c>                     : "ᵓ" U1D53 # MODIFIER LETTER SMALL OPEN O
<dead_circumflex> <U21BB> <a>                     : "ᵄ" U1D44 # MODIFIER LETTER SMALL TURNED A
<dead_circumflex> <Greek_alpha>                   : "ᵅ" U1D45 # MODIFIER LETTER SMALL ALPHA
<dead_circumflex> <U21BB> <Greek_alpha>           : "ᶛ" U1D9B # MODIFIER LETTER SMALL TURNED ALPHA
# non-IPA:
<dead_circumflex> <dead_stroke> <I>               : "ᶧ" U1DA7 # MODIFIER LETTER SMALL CAPITAL I WITH STROKE
<dead_circumflex> <Multi_key> <minus> <I>         : "ᶧ" U1DA7 # MODIFIER LETTER SMALL CAPITAL I WITH STROKE
<dead_circumflex> <dead_stroke> <Multi_key> <I> <I> : "ᶧ" U1DA7 # MODIFIER LETTER SMALL CAPITAL I WITH STROKE

# non-IPA Sinologist letters (to be included?)
<U21BB> <Multi_key> <r> <underscore>              : "ɿ" U027F # LATIN SMALL LETTER REVERSED R WITH FISHHOOK
<U21BB> <Multi_key> <s> <h>                       : "ʅ" U0285 # LATIN SMALL LETTER SQUAT REVERSED ESH
<dead_hook> <U21BB> <h>                           : "ʮ" U02AE # LATIN SMALL LETTER TURNED H WITH FISHHOOK
<dead_dasia> <dead_hook> <U21BB> <h>              : "ʯ" U02AF # LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL

# Vietnamese language
<dead_psili> <A>                                  : "Ả" U1EA2 # LATIN CAPITAL LETTER A WITH HOOK ABOVE
<dead_psili> <a>                                  : "ả" U1EA3 # LATIN SMALL LETTER A WITH HOOK ABOVE
<dead_psili> <E>                                  : "Ẻ" U1EBA # LATIN CAPITAL LETTER E WITH HOOK ABOVE
<dead_psili> <e>                                  : "ẻ" U1EBB # LATIN SMALL LETTER E WITH HOOK ABOVE
<dead_psili> <I>                                  : "Ỉ" U1EC8 # LATIN CAPITAL LETTER I WITH HOOK ABOVE
<dead_psili> <i>                                  : "ỉ" U1EC9 # LATIN SMALL LETTER I WITH HOOK ABOVE
<dead_psili> <O>                                  : "Ỏ" U1ECE # LATIN CAPITAL LETTER O WITH HOOK ABOVE
<dead_psili> <o>                                  : "ỏ" U1ECF # LATIN SMALL LETTER O WITH HOOK ABOVE
<dead_psili> <U>                                  : "Ủ" U1EE6 # LATIN CAPITAL LETTER U WITH HOOK ABOVE
<dead_psili> <u>                                  : "ủ" U1EE7 # LATIN SMALL LETTER U WITH HOOK ABOVE
<dead_psili> <Y>                                  : "Ỷ" U1EF6 # LATIN CAPITAL LETTER Y WITH HOOK ABOVE
<dead_psili> <y>                                  : "ỷ" U1EF7 # LATIN SMALL LETTER Y WITH HOOK ABOVE
<dead_psili> <dead_breve> <A>                     : "Ẳ" U1EB2 # LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE
<dead_psili> <dead_breve> <a>                     : "ẳ" U1EB3 # LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE
<dead_psili> <dead_circumflex> <A>                : "Ẩ" U1EA8 # LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
<dead_psili> <dead_circumflex> <a>                : "ẩ" U1EA9 # LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
<dead_psili> <dead_circumflex> <E>                : "Ể" U1EC2 # LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
<dead_psili> <dead_circumflex> <e>                : "ể" U1EC3 # LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
<dead_psili> <dead_circumflex> <O>                : "Ổ" U1ED4 # LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
<dead_psili> <dead_circumflex> <o>                : "ổ" U1ED5 # LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
<U02DE> <O>                                       : "Ơ" U01A0 # LATIN CAPITAL LETTER O WITH HORN
<U02DE> <o>                                       : "ơ" U01A1 # LATIN SMALL LETTER O WITH HORN
<dead_acute> <U02DE> <O>                          : "Ớ" U1EDA # LATIN CAPITAL LETTER O WITH HORN AND ACUTE
<dead_acute> <U02DE> <o>                          : "ớ" U1EDB # LATIN SMALL LETTER O WITH HORN AND ACUTE
<dead_grave> <U02DE> <O>                          : "Ờ" U1EDC # LATIN CAPITAL LETTER O WITH HORN AND GRAVE
<dead_grave> <U02DE> <o>                          : "ờ" U1EDD # LATIN SMALL LETTER O WITH HORN AND GRAVE
<dead_psili> <U02DE> <O>                          : "Ở" U1EDE # LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE
<dead_psili> <U02DE> <o>                          : "ở" U1EDF # LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
<dead_tilde> <U02DE> <O>                          : "Ỡ" U1EE0 # LATIN CAPITAL LETTER O WITH HORN AND TILDE
<dead_tilde> <U02DE> <o>                          : "ỡ" U1EE1 # LATIN SMALL LETTER O WITH HORN AND TILDE
<dead_belowdot> <U02DE> <O>                       : "Ợ" U1EE2 # LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
<dead_belowdot> <U02DE> <o>                       : "ợ" U1EE3 # LATIN SMALL LETTER O WITH HORN AND DOT BELOW
<U02DE> <U>                                       : "Ư" U01AF # LATIN CAPITAL LETTER U WITH HORN
<U02DE> <u>                                       : "ư" U01B0 # LATIN SMALL LETTER U WITH HORN
<dead_acute> <U02DE> <U>                          : "Ứ" U1EE8 # LATIN CAPITAL LETTER U WITH HORN AND ACUTE
<dead_acute> <U02DE> <u>                          : "ứ" U1EE9 # LATIN SMALL LETTER U WITH HORN AND ACUTE
<dead_grave> <U02DE> <U>                          : "Ừ" U1EEA # LATIN CAPITAL LETTER U WITH HORN AND GRAVE
<dead_grave> <U02DE> <u>                          : "ừ" U1EEB # LATIN SMALL LETTER U WITH HORN AND GRAVE
<dead_psili> <U02DE> <U>                          : "Ử" U1EEC # LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE
<dead_psili> <U02DE> <u>                          : "ử" U1EED # LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
<dead_tilde> <U02DE> <U>                          : "Ữ" U1EEE # LATIN CAPITAL LETTER U WITH HORN AND TILDE
<dead_tilde> <U02DE> <u>                          : "ữ" U1EEF # LATIN SMALL LETTER U WITH HORN AND TILDE
<dead_belowdot> <U02DE> <U>                       : "Ự" U1EF0 # LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
<dead_belowdot> <U02DE> <u>                       : "ự" U1EF1 # LATIN SMALL LETTER U WITH HORN AND DOT BELOW

# diacritics below
<Multi_key> <underscore> <dead_circumflex> <D>    : "Ḓ" U1E12 # LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <d>    : "ḓ" U1E13 # LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <L>    : "Ḽ" U1E3C # LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <l>    : "ḽ" U1E3D # LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <N>    : "Ṋ" U1E4A # LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <n>    : "ṋ" U1E4B # LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <T>    : "Ṱ" U1E70 # LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <t>    : "ṱ" U1E71 # LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <E>    : "Ḙ" U1E18 # LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <e>    : "ḙ" U1E19 # LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <U>    : "Ṷ" U1E76 # LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW
<Multi_key> <underscore> <dead_circumflex> <u>    : "ṷ" U1E77 # LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW
<U21BB> <dead_abovering> <A>                      : "Ḁ" U1E00 # LATIN CAPITAL LETTER A WITH RING BELOW
<U21BB> <dead_abovering> <a>                      : "ḁ" U1E01 # LATIN SMALL LETTER A WITH RING BELOW
<U21BB> <dead_diaeresis> <U>                      : "Ṳ" U1E72 # LATIN CAPITAL LETTER U WITH DIAERESIS BELOW
<U21BB> <dead_diaeresis> <u>                      : "ṳ" U1E73 # LATIN SMALL LETTER U WITH DIAERESIS BELOW
<U21BB> <dead_tilde> <E>                          : "Ḛ" U1E1A # LATIN CAPITAL LETTER E WITH TILDE BELOW
<U21BB> <dead_tilde> <e>                          : "ḛ" U1E1B # LATIN SMALL LETTER E WITH TILDE BELOW
<U21BB> <dead_tilde> <I>                          : "Ḭ" U1E2C # LATIN CAPITAL LETTER I WITH TILDE BELOW
<U21BB> <dead_tilde> <i>                          : "ḭ" U1E2D # LATIN SMALL LETTER I WITH TILDE BELOW
<U21BB> <dead_tilde> <U>                          : "Ṵ" U1E74 # LATIN CAPITAL LETTER U WITH TILDE BELOW
<U21BB> <dead_tilde> <u>                          : "ṵ" U1E75 # LATIN SMALL LETTER U WITH TILDE BELOW

# other letters
<Multi_key> <rightsinglequotemark> <n>            : "ŉ" U0149 # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
<Multi_key> <n> <bar>                             : "ƞ" U019E # LATIN SMALL LETTER N WITH LONG RIGHT LEG
<Multi_key> <N> <bar>                             : "Ƞ" U0220 # LATIN CAPITAL LETTER N WITH LONG RIGHT LEG
<Multi_key> <g> <U>                               : "Ȣ" U0222 # LATIN CAPITAL LETTER OU
<Multi_key> <G> <U>                               : "Ȣ" U0222 # LATIN CAPITAL LETTER OU
<Multi_key> <O> <U>                               : "Ȣ" U0222 # LATIN CAPITAL LETTER OU
<Multi_key> <Greek_OMICRON> <Greek_UPSILON>       : "Ȣ" U0222 # LATIN CAPITAL LETTER OU
<Multi_key> <Greek_omicron> <Greek_upsilon>       : "ȣ" U0223 # LATIN SMALL LETTER OU
<Multi_key> <g> <u>                               : "ȣ" U0223 # LATIN SMALL LETTER OU
<U21BB> <variation>                                : "ȣ" U0223 # LATIN SMALL LETTER OU
<Multi_key> <O> <o>                               : "ⱺ" U2C7A # LATIN SMALL LETTER O WITH LOW RING INSIDE
# need for better Cokos to generate these (analog: ♫i? → ʔ):
<Multi_key> <X> <question>                        : "Ɂ" U0241 # LATIN CAPITAL LETTER GLOTTAL STOP
<Multi_key> <x> <question>                        : "ɂ" U0242 # LATIN SMALL LETTER GLOTTAL STOP

# arabic numbers
<Multi_key> <a> <0>                               : "٠"   U0660 # ARABIC-INDIC DIGIT ZERO
<Multi_key> <a> <1>                               : "١"   U0661 # ARABIC-INDIC DIGIT ONE
<Multi_key> <a> <2>                               : "٢"   U0662 # ARABIC-INDIC DIGIT TWO
<Multi_key> <a> <3>                               : "٣"   U0663 # ARABIC-INDIC DIGIT THREE
<Multi_key> <a> <4>                               : "٤"   U0664 # ARABIC-INDIC DIGIT FOUR
<Multi_key> <a> <5>                               : "٥"   U0665 # ARABIC-INDIC DIGIT FIVE
<Multi_key> <a> <6>                               : "٦"   U0666 # ARABIC-INDIC DIGIT SIX
<Multi_key> <a> <7>                               : "٧"   U0667 # ARABIC-INDIC DIGIT SEVEN
<Multi_key> <a> <8>                               : "٨"   U0668 # ARABIC-INDIC DIGIT EIGHT
<Multi_key> <a> <9>                               : "٩"   U0669 # ARABIC-INDIC DIGIT NINE
<Multi_key> <a> <KP_0>                            : "٠"   U0660 # ARABIC-INDIC DIGIT ZERO
<Multi_key> <a> <KP_1>                            : "١"   U0661 # ARABIC-INDIC DIGIT ONE
<Multi_key> <a> <KP_2>                            : "٢"   U0662 # ARABIC-INDIC DIGIT TWO
<Multi_key> <a> <KP_3>                            : "٣"   U0663 # ARABIC-INDIC DIGIT THREE
<Multi_key> <a> <KP_4>                            : "٤"   U0664 # ARABIC-INDIC DIGIT FOUR
<Multi_key> <a> <KP_5>                            : "٥"   U0665 # ARABIC-INDIC DIGIT FIVE
<Multi_key> <a> <KP_6>                            : "٦"   U0666 # ARABIC-INDIC DIGIT SIX
<Multi_key> <a> <KP_7>                            : "٧"   U0667 # ARABIC-INDIC DIGIT SEVEN
<Multi_key> <a> <KP_8>                            : "٨"   U0668 # ARABIC-INDIC DIGIT EIGHT
<Multi_key> <a> <KP_9>                            : "٩"   U0669 # ARABIC-INDIC DIGIT NINE

# Medieval section
# will be included here with Ꝥꝥ, 
<dead_stroke> <U017F>                             : "ẜ" U1E9C # LATIN SMALL LETTER LONG S WITH DIAGONAL STROKE
<Multi_key> <slash> <U017F>                       : "ẜ" U1E9C # LATIN SMALL LETTER LONG S WITH DIAGONAL STROKE
<Multi_key> <H> <V>                               : "Ƕ" U01F6 # LATIN CAPITAL LETTER HWAIR
<Multi_key> <H> <v>                               : "Ƕ" U01F6 # LATIN CAPITAL LETTER HWAIR
<Multi_key> <h> <v>                               : "ƕ" U0195 # LATIN SMALL LETTER HV
<Multi_key> <W> <Y>                               : "Ƿ" U01F7 # LATIN CAPITAL LETTER WYNN
<Multi_key> <W> <y>                               : "Ƿ" U01F7 # LATIN CAPITAL LETTER WYNN
<Multi_key> <w> <y>                               : "ƿ" U01BF # LATIN LETTER WYNN
<Multi_key> <Y> <G>                               : "Ȝ" U021C # LATIN CAPITAL LETTER YOGH
<Multi_key> <Y> <g>                               : "Ȝ" U021C # LATIN CAPITAL LETTER YOGH
<Multi_key> <y> <g>                               : "ȝ" U021D # LATIN SMALL LETTER YOGH
#<U21BB> <Greek_delta>                             : "ƍ" U018D # LATIN SMALL LETTER TURNED DELTA
#<U21BB> <g>                                       : "ᵷ" U1D77 # LATIN SMALL LETTER TURNED G
#<Multi_key> <y> <r>                               : "Ʀ" U01A6 # LATIN LETTER YR

# End of additional Definitions (languages) by Neo keyboard layout
