#configinfo IPA (int. phonetic alphabet) und weitere Sprachen ([neːo] ɕ ɚ Ʈ)

# IPA-Compose by aleχ, 2009, CC-BY-SA DE 3.
<Multi_key> <B> <B>                               : "ʙ" U0299 # LATIN LETTER SMALL CAPITAL B
<Multi_key> <G> <G>                               : "ɢ" U0262 # LATIN LETTER SMALL CAPITAL G
<Multi_key> <H> <H>                               : "ʜ" U029C # LATIN LETTER SMALL CAPITAL H
<Multi_key> <I> <I>                               : "ɪ" U026A # LATIN LETTER SMALL CAPITAL I
<Multi_key> <L> <L>                               : "ʟ" U029F # LATIN LETTER SMALL CAPITAL L
<Multi_key> <N> <N>                               : "ɴ" U0274 # LATIN LETTER SMALL CAPITAL N
<Multi_key> <R> <R>                               : "ʀ" U0280 # LATIN LETTER SMALL CAPITAL R
<Multi_key> <Y> <Y>                               : "ʏ" U028F # LATIN LETTER SMALL CAPITAL Y
<Multi_key> <O> <O> <E>                           : "ɶ" U0276 # LATIN LETTER SMALL CAPITAL OE

<Multi_key> <a> <a>                               : "ɑ" U0251 # LATIN SMALL LETTER ALPHA
<Multi_key> <Greek_alpha> <Greek_alpha>           : "ɑ" U0251 # LATIN SMALL LETTER ALPHA
<Multi_key> <Greek_epsilon> <Greek_epsilon>       : "ɛ" U025B # LATIN SMALL LETTER OPEN E
<Multi_key> <v> <parenright>                      : "ʋ" U028B # LATIN SMALL LETTER V WITH HOOK
<Multi_key> <n> <l>                               : "ɳ" U0273 # LATIN SMALL LETTER N WITH RETROFLEX HOOK
<Multi_key> <Greek_phi> <Greek_phi>               : "ɸ" U0278 # LATIN SMALL LETTER PHI
<Multi_key> <Greek_PHI> <Greek_PHI>               : "ɸ" U0278 # LATIN SMALL LETTER PHI
<Multi_key> <U03D5> <U03D5>                       : "ɸ" U0278 # LATIN SMALL LETTER PHI
<Multi_key> <Greek_upsilon> <Greek_upsilon>       : "ʊ" U028A # LATIN SMALL LETTER UPSILON
<Multi_key> <3> <3>                               : "ɜ" U025C # LATIN SMALL LETTER REVERSED OPEN E
<Multi_key> <KP_3> <KP_3>                         : "ɜ" U025C # LATIN SMALL LETTER REVERSED OPEN E
<Multi_key> <g> <g>                               : "ɡ" U0261 # LATIN SMALL LETTER SCRIPT G
#<U21BB> <parenright>                              : "‿" U203F # UNDERTIE
#<U21BB> <parenleft>                               : "͡" U0361 # COMBINING DOUBLE INVERTED BREVE
<U21BB> <Greek_tau>                               : "ɾ" U027E # LATIN SMALL LETTER R WITH FISHHOOK
<Multi_key> <r> <underscore>                      : "ɾ" U027E # LATIN SMALL LETTER R WITH FISHHOOK
<Multi_key> <r> <underbar>                        : "ɾ" U027E # LATIN SMALL LETTER R WITH FISHHOOK
<U21BB> <Multi_key> <r> <r>                       : "ɺ" U027A # LATIN SMALL LETTER TURNED R WITH LONG LEG
<U21BB> <Multi_key> <a> <a>                       : "ɒ" U0252 # LATIN SMALL LETTER TURNED ALPHA
<U21BB> <Multi_key> <Greek_alpha> <Greek_alpha>   : "ɒ" U0252 # LATIN SMALL LETTER TURNED ALPHA

<Multi_key> <l> <l>                               : "ɭ" U026D # LATIN SMALL LETTER L WITH RETROFLEX HOOK
<Multi_key> <r> <r>                               : "ɼ" U027C # LATIN SMALL LETTER R WITH LONG LEG
<Multi_key> <t> <l>                               : "ʈ" U0288 # LATIN SMALL LETTER T WITH RETROFLEX HOOK

# IPA hook letters
<U02DE> <Multi_key> <G> <G>                       : "ʛ" U029B # LATIN LETTER SMALL CAPITAL G WITH HOOK
<Multi_key> <Greek_gamma> <Greek_gamma>           : "ɣ" U0263 # LATIN SMALL LETTER GAMMA
<U02DE> <Multi_key> <e> <e>                       : "ɚ" U025A # LATIN SMALL LETTER SCHWA WITH HOOK
<U02DE> <3>                                       : "ɝ" U025D # LATIN SMALL LETTER REVERSED OPEN E WITH HOOK

<dead_stroke> <J>                                 : "ɟ" U025F # LATIN SMALL LETTER DOTLESS J WITH STROKE
<dead_stroke> <j>                                 : "ɟ" U025F # LATIN SMALL LETTER DOTLESS J WITH STROKE
#<U02DE> <dead_stroke> <J>                         : "ʄ" U0284 # LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK
<Multi_key> <j> <f>                               : "ʄ" U0284 # LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK
<Multi_key> <minus> <o>                           : "ɵ" U0275 # LATIN SMALL LETTER BARRED O

<dead_abovering> <c>                              : "ɕ" U0255 # LATIN SMALL LETTER C WITH CURL
<dead_abovering> <z>                              : "ʑ" U0291 # LATIN SMALL LETTER Z WITH CURL
# nonstandard sinologist symbols:
<dead_abovering> <d>                              : "ȡ" U0221 # LATIN SMALL LETTER D WITH CURL
<dead_abovering> <l>                              : "ȴ" U0234 # LATIN SMALL LETTER L WITH CURL
<dead_abovering> <n>                              : "ȵ" U0235 # LATIN SMALL LETTER N WITH CURL
<dead_abovering> <t>                              : "ȶ" U0236 # LATIN SMALL LETTER T WITH CURL

<Multi_key> <l> <z>                               : "ɮ" U026E # LATIN SMALL LETTER LEZH
<Multi_key> <parenleft> <3> <space>               : "ɞ" U025E # LATIN SMALL LETTER CLOSED REVERSED OPEN E
<Multi_key> <parenleft> <KP_3> <space>            : "ɞ" U025E # LATIN SMALL LETTER CLOSED REVERSED OPEN E

<Multi_key> <0> <period>                          : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<Multi_key> <KP_0> <period>                       : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<Multi_key> <period> <0>                          : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<Multi_key> <period> <KP_0>                       : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<dead_abovedot> <0>                               : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<dead_abovedot> <KP_0>                            : "ʘ" U0298 # LATIN LETTER BILABIAL CLICK
<Multi_key> <x> <underscore>                      : "ɤ" U0264 # LATIN SMALL LETTER RAMS HORN
<Multi_key> <x> <underbar>                        : "ɤ" U0264 # LATIN SMALL LETTER RAMS HORN

<U02DE> <U21BB> <r>                               : "ɻ" U027B # LATIN SMALL LETTER TURNED R WITH HOOK
<Multi_key> <j> <n>                               : "ɲ" U0272 # LATIN SMALL LETTER N WITH LEFT HOOK
# überschreibt ㎗, verwende ♫dℓ
<Multi_key> <d> <l>                               : "ɖ" U0256 # LATIN SMALL LETTER D WITH TAIL
<Multi_key> <U02DE> <h> <j>                       : "ɧ" U0267 # LATIN SMALL LETTER HENG WITH HOOK
<U21BB> <Multi_key> <h> <n>                       : "ɰ" U0270 # LATIN SMALL LETTER TURNED M WITH LONG LEG

<Multi_key> <i> <question>                        : "ʔ" U0294 # LATIN LETTER GLOTTAL STOP
<dead_stroke> <Multi_key> <i> <question>          : "ʡ" U02A1 # LATIN LETTER GLOTTAL STOP WITH STROKE
<U21BB> <Multi_key> <i> <question>                : "ʕ" U0295 # LATIN LETTER PHARYNGEAL VOICED FRICATIVE
<dead_stroke> <U21BB> <question>                  : "ʢ" U02A2 # LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE
<dead_stroke> <U21BB> <Multi_key> <i> <question>  : "ʢ" U02A2 # LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE

<Multi_key> <colon> <colon>                       : "ː" U02D0 # MODIFIER LETTER TRIANGULAR COLON
<Multi_key> <periodcentered> <periodcentered>     : "ˑ" U02D1 # MODIFIER LETTER HALF TRIANGULAR COLON
<Multi_key> <apostrophe> <apostrophe>             : "ˈ" U02C8 # MODIFIER LETTER VERTICAL LINE
<Multi_key> <underscore> <apostrophe>             : "ˌ" U02CC # MODIFIER LETTER LOW VERTICAL LINE
<Multi_key> <underbar> <apostrophe>               : "ˌ" U02CC # MODIFIER LETTER LOW VERTICAL LINE
<U21BB> <Multi_key> <apostrophe> <apostrophe>     : "ˌ" U02CC # MODIFIER LETTER LOW VERTICAL LINE

<Multi_key> <t> <5>                               : "˥" U02E5 # MODIFIER LETTER EXTRA-HIGH TONE BAR
<Multi_key> <t> <4>                               : "˦" U02E6 # MODIFIER LETTER HIGH TONE BAR
<Multi_key> <t> <3>                               : "˧" U02E7 # MODIFIER LETTER MID TONE BAR
<Multi_key> <t> <2>                               : "˨" U02E8 # MODIFIER LETTER LOW TONE BAR
<Multi_key> <t> <1>                               : "˩" U02E9 # MODIFIER LETTER EXTRA-LOW TONE BAR

# Standard Mandarin tones
#<Multi_key> <m> <1>                               : "˥˥"
#<Multi_key> <m> <2>                               : "˧˥"
#<Multi_key> <m> <3>                               : "˨˩˦"
#<Multi_key> <m> <4>                               : "˥˩"

<dead_circumflex> <Multi_key> <bar> <asciicircum> : "ꜛ" UA71B # MODIFIER LETTER RAISED UP ARROW
<dead_circumflex> <Multi_key> <v> <bar>           : "ꜜ" UA71C # MODIFIER LETTER RAISED DOWN ARROW
<dead_circumflex> <U21BB> <L>                     : "̚" U031A # COMBINING LEFT ANGLE ABOVE

<Multi_key> <equal> <bar> <equal>                 : "ǂ" U01C2 # LATIN LETTER ALVEOLAR CLICK
<Multi_key> <KP_Equal> <bar> <KP_Equal>           : "ǂ" U01C2 # LATIN LETTER ALVEOLAR CLICK
<Multi_key> <i> <bar> <space>                     : "ǀ" U01C0 # LATIN LETTER DENTAL CLICK
<Multi_key> <i> <bar> <bar>                       : "ǁ" U01C1 # LATIN LETTER LATERAL CLICK
<Multi_key> <i> <exclam>                          : "ǃ" U01C3 # LATIN LETTER RETROFLEX CLICK

# Diakritika – erstmal zum Testen:
<U21BB> <degree>                                  : "̥" U0325 # COMBINING RING BELOW
<Multi_key> <underscore> <degree>                 : "̥" U0325 # COMBINING RING BELOW
<Multi_key> <underbar> <degree>                   : "̥" U0325 # COMBINING RING BELOW
<U21BB> <quotedbl>                                : "̤" U0324 # COMBINING DIAERESIS BELOW
<Multi_key> <underscore> <quotedbl>               : "̤" U0324 # COMBINING DIAERESIS BELOW
<Multi_key> <underbar> <quotedbl>                 : "̤" U0324 # COMBINING DIAERESIS BELOW
<U21BB> <asciitilde>                              : "̰" U0330 # COMBINING TILDE BELOW
<Multi_key> <underscore> <asciitilde>             : "̰" U0330 # COMBINING TILDE BELOW
<Multi_key> <underbar> <asciitilde>               : "̰" U0330 # COMBINING TILDE BELOW
#<Multi_key> <underscore> <breve>                  : "̯" U032F # COMBINING INVERTED BREVE BELOW

#<Multi_key> <underscore> <bracketleft> <bracketright> : "̻" U033B # COMBINING SQUARE BELOW
#<Multi_key> <underbar> <bracketleft> <bracketright>   : "̻" U033B # COMBINING SQUARE BELOW
<Multi_key> <underscore> <U21BB> <bracketright>   : "̺" U033A # COMBINING INVERTED BRIDGE BELOW
<Multi_key> <underbar> <U21BB> <bracketright>     : "̺" U033A # COMBINING INVERTED BRIDGE BELOW
<Multi_key> <underscore> <U21BB> <bracketleft>    : "̪" U032A # COMBINING BRIDGE BELOW
<Multi_key> <underbar> <U21BB> <bracketleft>      : "̪" U032A # COMBINING BRIDGE BELOW

# Hochgestellt:
<dead_circumflex> <U02DE> <m>                     : "ᶬ" U1DAC # MODIFIER LETTER SMALL M WITH HOOK
<dead_circumflex> <Multi_key> <n> <l>             : "ᶯ" U1DAF # MODIFIER LETTER SMALL N WITH RETROFLEX HOOK
<dead_circumflex> <Multi_key> <j> <n>             : "ᶮ" U1DAE # MODIFIER LETTER SMALL N WITH LEFT HOOK
<dead_circumflex> <U02DE> <n>                     : "ᵑ" U1D51 # MODIFIER LETTER SMALL ENG
<dead_circumflex> <Multi_key> <n> <g>             : "ᵑ" U1D51 # MODIFIER LETTER SMALL ENG
<dead_circumflex> <Multi_key> <N> <N>             : "ᶰ" U1DB0 # MODIFIER LETTER SMALL CAPITAL N
<dead_circumflex> <dead_stroke> <j>               : "ᶡ" U1DA1 # MODIFIER LETTER SMALL DOTLESS J WITH STROKE
<dead_circumflex> <dead_stroke> <J>               : "ᶡ" U1DA1 # MODIFIER LETTER SMALL DOTLESS J WITH STROKE
<dead_circumflex> <Multi_key> <g> <g>             : "ᶢ" U1DA2 # MODIFIER LETTER SMALL SCRIPT G
<dead_circumflex> <question>                      : "ˀ" U02C0 # MODIFIER LETTER GLOTTAL STOP
<dead_circumflex> <U03D5>                         : "ᶲ" U1DB2 # MODIFIER LETTER SMALL PHI
<dead_circumflex> <Multi_key> <d> <h>             : "ᶞ" U1D9E # MODIFIER LETTER SMALL ETH
<dead_circumflex> <Multi_key> <s> <h>             : "ᶴ" U1DB4 # MODIFIER LETTER SMALL ESH
<dead_circumflex> <Multi_key> <z> <h>             : "ᶾ" U1DBE # MODIFIER LETTER SMALL EZH
<dead_circumflex> <Multi_key> <z> <z>             : "ᶾ" U1DBE # MODIFIER LETTER SMALL EZH
<dead_circumflex> <U02DE> <s>                     : "ᶳ" U1DB3 # MODIFIER LETTER SMALL S WITH HOOK
<dead_circumflex> <U02DE> <z>                     : "ᶼ" U1DBC # MODIFIER LETTER SMALL Z WITH RETROFLEX HOOK
<dead_circumflex> <U02DE> <j>                     : "ᶨ" U1DA8 # MODIFIER LETTER SMALL J WITH CROSSED-TAIL
<dead_circumflex> <U02DE> <x>                     : "ˠ" U02E0 # MODIFIER LETTER SMALL GAMMA
<dead_circumflex> <U21BB> <R>                     : "ʶ" U02B6 # MODIFIER LETTER SMALL CAPITAL INVERTED R
<dead_circumflex> <U21BB> <question>              : "ˁ" U02C1 # MODIFIER LETTER REVERSED GLOTTAL STOP
<dead_circumflex> <U02DE> <h>                     : "ʱ" U02B1 # MODIFIER LETTER SMALL H WITH HOOK
<dead_circumflex> <Multi_key> <v> <parenright>    : "ᶹ" U1DB9 # MODIFIER LETTER SMALL V WITH HOOK
<dead_circumflex> <U21BB> <r>                     : "ʴ" U02B4 # MODIFIER LETTER SMALL TURNED R
<dead_circumflex> <U02DE> <U21BB> <r>             : "ʵ" U02B5 # MODIFIER LETTER SMALL TURNED R WITH HOOK
<dead_circumflex> <U21BB> <Multi_key> <h> <n>     : "ᶭ" U1DAD # MODIFIER LETTER SMALL TURNED M WITH LONG LEG
<dead_circumflex> <Multi_key> <l> <l>             : "ᶩ" U1DA9 # MODIFIER LETTER SMALL L WITH RETROFLEX HOOK
<dead_circumflex> <Multi_key> <L> <L>             : "ᶫ" U1DAB # MODIFIER LETTER SMALL CAPITAL L
<dead_circumflex> <U21BB> <h>                     : "ᶣ" U1DA3 # MODIFIER LETTER SMALL TURNED H
<dead_circumflex> <dead_abovering> <c>            : "ᶝ" U1D9D # MODIFIER LETTER SMALL C WITH CURL
<dead_circumflex> <dead_abovering> <z>            : "ᶽ" U1DBD # MODIFIER LETTER SMALL Z WITH CURL
<dead_circumflex> <dead_stroke> <i>               : "ᶤ" U1DA4 # MODIFIER LETTER SMALL I WITH STROKE
<dead_circumflex> <dead_stroke> <u>               : "ᶶ" U1DB6 # MODIFIER LETTER SMALL U BAR
<dead_circumflex> <U21BB> <m>                     : "ᵚ" U1D5A # MODIFIER LETTER SMALL TURNED M
<dead_circumflex> <Multi_key> <I> <I>             : "ᶦ" U1DA6 # MODIFIER LETTER SMALL CAPITAL I
<dead_circumflex> <Greek_upsilon>                 : "ᶷ" U1DB7 # MODIFIER LETTER SMALL UPSILON
<dead_circumflex> <Multi_key> <minus> <o>         : "ᶱ" U1DB1 # MODIFIER LETTER SMALL BARRED O
<dead_circumflex> <Multi_key> <e> <e>             : "ᵊ" U1D4A # MODIFIER LETTER SMALL SCHWA
<dead_circumflex> <Greek_epsilon>                 : "ᵋ" U1D4B # MODIFIER LETTER SMALL OPEN E
<dead_circumflex> <Multi_key> <3> <3>             : "ᶟ" U1D9F # MODIFIER LETTER SMALL REVERSED OPEN E
<dead_circumflex> <U21BB> <v>                     : "ᶺ" U1DBA # MODIFIER LETTER SMALL TURNED V
<dead_circumflex> <U21BB> <c>                     : "ᵓ" U1D53 # MODIFIER LETTER SMALL OPEN O
<dead_circumflex> <U21BB> <a>                     : "ᵄ" U1D44 # MODIFIER LETTER SMALL TURNED A
<dead_circumflex> <Greek_alpha>                   : "ᵅ" U1D45 # MODIFIER LETTER SMALL ALPHA
<dead_circumflex> <U21BB> <Greek_alpha>           : "ᶛ" U1D9B # MODIFIER LETTER SMALL TURNED ALPHA

# Andere Sprachen
<Multi_key> <Z> <H>                               : "Ʒ"   U01B7 # LATIN CAPITAL LETTER EZH
<Multi_key> <Z> <Z>                               : "Ʒ"   U01B7 # LATIN CAPITAL LETTER EZH
<dead_caron> <Multi_key> <Z> <H>                  : "Ǯ"   U01EE # LATIN CAPITAL LETTER EZH WITH CARON
<dead_caron> <Multi_key> <z> <h>                  : "ǯ"   U01EF # LATIN SMALL LETTER EZH WITH CARON

# Afrikanisch
<Multi_key> <D> <l>                               : "Ɖ" U0189 # LATIN CAPITAL LETTER AFRICAN D
<Multi_key> <T> <l>                               : "Ʈ" U01AE # LATIN CAPITAL LETTER T WITH RETROFLEX HOOK
<Multi_key> <V> <parenright>                      : "Ʋ" U01B2 # LATIN CAPITAL LETTER V WITH HOOK
<U21BB> <Multi_key> <Z> <Z>                       : "Ƹ" U01B8 # LATIN CAPITAL LETTER EZH REVERSED
<U21BB> <Multi_key> <z> <z>                       : "ƹ" U01B9 # LATIN SMALL LETTER EZH REVERSED
<Multi_key> <j> <N>                               : "Ɲ" U019D # LATIN CAPITAL LETTER N WITH LEFT HOOK
<Multi_key> <S> <H>                               : "Ʃ"   U01A9 # LATIN CAPITAL LETTER ESH
#Ǝǝ ↻E?		Pan-nigerian (Ǝ ≠ ∃, ǝ ≠ ə) 018E LATIN CAPITAL LETTER REVERSED E

# arabic numbers
<Multi_key> <a> <0>                      : "٠"   U0660 # ARABIC-INDIC DIGIT ZERO
<Multi_key> <a> <1>                      : "١"   U0661 # ARABIC-INDIC DIGIT ONE
<Multi_key> <a> <2>                      : "٢"   U0662 # ARABIC-INDIC DIGIT TWO
<Multi_key> <a> <3>                      : "٣"   U0663 # ARABIC-INDIC DIGIT THREE
<Multi_key> <a> <4>                      : "٤"   U0664 # ARABIC-INDIC DIGIT FOUR
<Multi_key> <a> <5>                      : "٥"   U0665 # ARABIC-INDIC DIGIT FIVE
<Multi_key> <a> <6>                      : "٦"   U0666 # ARABIC-INDIC DIGIT SIX
<Multi_key> <a> <7>                      : "٧"   U0667 # ARABIC-INDIC DIGIT SEVEN
<Multi_key> <a> <8>                      : "٨"   U0668 # ARABIC-INDIC DIGIT EIGHT
<Multi_key> <a> <9>                      : "٩"   U0669 # ARABIC-INDIC DIGIT NINE
<Multi_key> <a> <KP_0>                   : "٠"   U0660 # ARABIC-INDIC DIGIT ZERO
<Multi_key> <a> <KP_1>                   : "١"   U0661 # ARABIC-INDIC DIGIT ONE
<Multi_key> <a> <KP_2>                   : "٢"   U0662 # ARABIC-INDIC DIGIT TWO
<Multi_key> <a> <KP_3>                   : "٣"   U0663 # ARABIC-INDIC DIGIT THREE
<Multi_key> <a> <KP_4>                   : "٤"   U0664 # ARABIC-INDIC DIGIT FOUR
<Multi_key> <a> <KP_5>                   : "٥"   U0665 # ARABIC-INDIC DIGIT FIVE
<Multi_key> <a> <KP_6>                   : "٦"   U0666 # ARABIC-INDIC DIGIT SIX
<Multi_key> <a> <KP_7>                   : "٧"   U0667 # ARABIC-INDIC DIGIT SEVEN
<Multi_key> <a> <KP_8>                   : "٨"   U0668 # ARABIC-INDIC DIGIT EIGHT
<Multi_key> <a> <KP_9>                   : "٩"   U0669 # ARABIC-INDIC DIGIT NINE
