#configinfo Ligaturen in der der Private-Use-Area (      )

# ligatures
<Multi_key> <f> <b>                      : ""   UE030 # LATIN SMALL LIGATURE FB
<Multi_key> <F> <b>                      : ""   UE031 # LATIN SMALL LIGATURE FFB
<Multi_key> <F> <h>                      : ""   UE032 # LATIN SMALL LIGATURE FFH
<Multi_key> <F> <j>                      : ""   UE033 # LATIN SMALL LIGATURE FFJ
<Multi_key> <F> <k>                      : ""   UE034 # LATIN SMALL LIGATURE FFK
<Multi_key> <F> <t>                      : ""   UE035 # LATIN SMALL LIGATURE FFT
<Multi_key> <f> <h>                      : ""   UE036 # LATIN SMALL LIGATURE FH
<Multi_key> <f> <j>                      : ""   UE037 # LATIN SMALL LIGATURE FJ
<Multi_key> <f> <k>                      : ""   UE038 # LATIN SMALL LIGATURE FK
<Multi_key> <f> <t>                      : ""   UE039 # LATIN SMALL LIGATURE FT
<Multi_key> <l> <c> <k>                  : ""   UE03A # LATIN SMALL LIGATURE CK
<Multi_key> <l> <c> <h>                  : ""   UE03B # LATIN SMALL LIGATURE CH
<Multi_key> <t> <t>                      : ""   UE03C # LATIN SMALL LIGATURE TT
<Multi_key> <l> <c> <t>                  : ""   UE03D # LATIN SMALL LIGATURE CT
<Multi_key> <U017F> <i>                  : ""   UE03E # LATIN SMALL LIGATURE LONG S I
<Multi_key> <U017F> <U017F>              : ""   UE03F # LATIN SMALL LIGATURE LONG S LONG S
<Multi_key> <U017F> <l>                  : ""   UE043 # LATIN SMALL LIGATURE LONG S L
<Multi_key> <S> <i>                      : ""   UE044 # LATIN SMALL LIGATURE LONG S LONG S I
<Multi_key> <U017F> <s>                  : ""   UE045 # LATIN SMALL LIGATURE LONG S S (GLYPH VARIANT OF SHARP S)
<Multi_key> <t> <z>                      : ""   UE04A # LATIN SMALL LIGATURE TZ (ALSO: UE04F)
<Multi_key> <Q> <u>                      : ""   UE048 # LATIN CAPITAL LETTER Q WITH SMALL LETTER U
<Multi_key> <T> <h>                      : ""   UE049 # LATIN CAPITAL LETTER T WITH SMALL LETTER H

# End of ligatures.module