#configinfo Physikalische square units (CJK-Kompatibilität) (㎕ ㎖ ㎗ ㎘ ㎙ ㎚ ㎛)

# physical square units
<Multi_key> <Greek_mu> <l>                : "㎕"   U3395 # SQUARE MU L
<Multi_key> <Greek_mu> <U2113>            : "㎕"   U3395 # SQUARE MU L
<Multi_key> <m> <l>                       : "㎖"   U3396 # SQUARE ML
<Multi_key> <m> <U2113>                   : "㎖"   U3396 # SQUARE ML
<Multi_key> <d> <l>                       : "㎗"   U3397 # SQUARE DL
<Multi_key> <d> <U2113>                   : "㎗"   U3397 # SQUARE DL
<Multi_key> <k> <l>                       : "㎘"   U3398 # SQUARE KL
<Multi_key> <k> <U2113>                   : "㎘"   U3398 # SQUARE KL
<Multi_key> <f> <m>                       : "㎙"   U3399 # SQUARE FM
<Multi_key> <n> <m>                       : "㎚"   U339A # SQUARE NM
<Multi_key> <Greek_mu> <m>                : "㎛"   U339B # SQUARE MU M
<Multi_key> <m> <m>                       : "㎜"   U339C # SQUARE MM
<Multi_key> <c> <m>                       : "㎝"   U339D # SQUARE CM
<Multi_key> <k> <m>                       : "㎞"   U339E # SQUARE KM
<Multi_key> <Greek_mu> <g>                : "㎍"   U338D # SQUARE MU G
<Multi_key> <m> <g>                       : "㎎"   U338E # SQUARE MG
<Multi_key> <k> <g>                       : "㎏"   U338F # SQUARE KG
<Multi_key> <H> <z>                       : "㎐"   U3390 # SQUARE HZ
<Multi_key> <k> <H> <z>                   : "㎑"   U3391 # SQUARE KHZ
<Multi_key> <M> <H> <z>                   : "㎒"   U3392 # SQUARE MHZ
<Multi_key> <2> <m> <m>                   : "㎟"   U339F # SQUARE MM SQUARED
<Multi_key> <2> <c> <m>                   : "㎠"   U33A0 # SQUARE CM SQUARED
<Multi_key> <2> <m> <space>               : "㎡"   U33A1 # SQUARE M SQUARED
<Multi_key> <2> <k> <m>                   : "㎢"   U33A2 # SQUARE KM SQUARED
<Multi_key> <KP_2> <m> <m>                : "㎟"   U339F # SQUARE MM SQUARED
<Multi_key> <KP_2> <c> <m>                : "㎠"   U33A0 # SQUARE CM SQUARED
<Multi_key> <KP_2> <m> <space>            : "㎡"   U33A1 # SQUARE M SQUARED
<Multi_key> <KP_2> <k> <m>                : "㎢"   U33A2 # SQUARE KM SQUARED
<Multi_key> <3> <m> <m>                   : "㎣"   U33A3 # SQUARE MM CUBED
<Multi_key> <3> <c> <m>                   : "㎤"   U33A4 # SQUARE CM CUBED
<Multi_key> <3> <m> <space>               : "㎥"   U33A5 # SQUARE M CUBED
<Multi_key> <3> <k> <m>                   : "㎦"   U33A6 # SQUARE KM CUBED
<Multi_key> <KP_3> <m> <m>                : "㎣"   U33A3 # SQUARE MM CUBED
<Multi_key> <KP_3> <c> <m>                : "㎤"   U33A4 # SQUARE CM CUBED
<Multi_key> <KP_3> <m> <space>            : "㎥"   U33A5 # SQUARE M CUBED
<Multi_key> <KP_3> <k> <m>                : "㎦"   U33A6 # SQUARE KM CUBED
<Multi_key> <m> <s>                       : "㎧"   U33A7 # SQUARE M OVER S
<Multi_key> <m> <2> <s>                   : "㎨"   U33A8 # SQUARE M OVER S SQUARED
<Multi_key> <m> <KP_2> <s>                : "㎨"   U33A8 # SQUARE M OVER S SQUARED
<Multi_key> <m> <o> <l>                   : "㏖"   U33D6 # SQUARE MOL

# End of squareunits.module