
// pointers to button objects on the GUI
pKeyButton[VK_TAB]=&but_tab;
pKeyButton[VK_CAPITAL]=&but_capslock;
pKeyButton[VK_LSHIFT]=&but_lshift;
pKeyButton[VK_LCONTROL]=&but_lctrl;
pKeyButton[VK_LWIN]=&but_lwin;
pKeyButton[VK_LMENU]=&but_lalt;
pKeyButton[VK_SPACE]=&but_space;
pKeyButton[VK_RMENU]=&but_altgr;
pKeyButton[VK_RWIN]=&but_rwin;
pKeyButton[VK_APPS]=&but_contmenu;
pKeyButton[VK_RCONTROL]=&but_rctrl;
pKeyButton[VK_RSHIFT]=&but_rshift;
pKeyButton[VK_RETURN]=&but_enter;
pKeyButton[VK_BACK]=&but_backspace;

pKeyButton[VK_0]=&but_0;
pKeyButton[VK_1]=&but_1;
pKeyButton[VK_2]=&but_2;
pKeyButton[VK_3]=&but_3;
pKeyButton[VK_4]=&but_4;
pKeyButton[VK_5]=&but_5;
pKeyButton[VK_6]=&but_6;
pKeyButton[VK_7]=&but_7;
pKeyButton[VK_8]=&but_8;
pKeyButton[VK_9]=&but_9;

pKeyButton[VK_A]=&but_A;
pKeyButton[VK_B]=&but_B;
pKeyButton[VK_C]=&but_C;
pKeyButton[VK_D]=&but_D;
pKeyButton[VK_E]=&but_E;
pKeyButton[VK_F]=&but_F;
pKeyButton[VK_G]=&but_G;
pKeyButton[VK_H]=&but_H;
pKeyButton[VK_I]=&but_I;
pKeyButton[VK_J]=&but_J;
pKeyButton[VK_K]=&but_K;
pKeyButton[VK_L]=&but_L;
pKeyButton[VK_M]=&but_M;
pKeyButton[VK_N]=&but_N;
pKeyButton[VK_O]=&but_O;
pKeyButton[VK_P]=&but_P;
pKeyButton[VK_Q]=&but_Q;
pKeyButton[VK_R]=&but_R;
pKeyButton[VK_S]=&but_S;
pKeyButton[VK_T]=&but_T;
pKeyButton[VK_U]=&but_U;
pKeyButton[VK_V]=&but_V;
pKeyButton[VK_W]=&but_W;
pKeyButton[VK_X]=&but_X;
pKeyButton[VK_Y]=&but_Y;
pKeyButton[VK_Z]=&but_Z;

pKeyButton[VK_UE]=&but_UE;
pKeyButton[VK_PLUS]=&but_plus;
pKeyButton[VK_COMMA]=&but_comma;
pKeyButton[VK_DASH]=&but_dash;
pKeyButton[VK_DOT]=&but_dot;
pKeyButton[VK_HASH]=&but_hash;
pKeyButton[VK_OE]=&but_OE;
pKeyButton[VK_SZ]=&but_sz;
pKeyButton[VK_CIRCUMFLEX]=&but_circ;
pKeyButton[VK_ACUT]=&but_acut;
pKeyButton[VK_AE]=&but_AE;
pKeyButton[VK_SMALLER]=&but_smaller;




keyFinger[VK_0]=4;
keyFinger[VK_1]=5;
keyFinger[VK_2]=5;
keyFinger[VK_3]=4;
keyFinger[VK_4]=3;
keyFinger[VK_5]=2;
keyFinger[VK_6]=2;
keyFinger[VK_7]=2;
keyFinger[VK_8]=2;
keyFinger[VK_9]=3;

keyFinger[VK_A]=5;
keyFinger[VK_B]=2;
keyFinger[VK_C]=3;
keyFinger[VK_D]=3;
keyFinger[VK_E]=3;
keyFinger[VK_F]=2;
keyFinger[VK_G]=2;
keyFinger[VK_H]=2;
keyFinger[VK_I]=3;
keyFinger[VK_J]=2;
keyFinger[VK_K]=3;
keyFinger[VK_L]=4;
keyFinger[VK_M]=2;
keyFinger[VK_N]=2;
keyFinger[VK_O]=4;
keyFinger[VK_P]=5;
keyFinger[VK_Q]=5;
keyFinger[VK_R]=2;
keyFinger[VK_S]=4;
keyFinger[VK_T]=2;
keyFinger[VK_U]=2;
keyFinger[VK_V]=2;
keyFinger[VK_W]=4;
keyFinger[VK_X]=4;
keyFinger[VK_Y]=5;
keyFinger[VK_Z]=2;

keyFinger[VK_UE]=5;
keyFinger[VK_PLUS]=5;
keyFinger[VK_COMMA]=3;
keyFinger[VK_DASH]=5;
keyFinger[VK_DOT]=4;
keyFinger[VK_OE]=5;
keyFinger[VK_SZ]=5;
keyFinger[VK_CIRCUMFLEX]=5;
keyFinger[VK_ACUT]=5;
keyFinger[VK_AE]=5;

keyFinger[VK_SPACE]=6;
