#define VK_MOD_2 VK_SHIFT
#define VK_MOD_21 VK_LSHIFT
#define VK_MOD_22 VK_RSHIFT
#define VK_MOD_31 VK_CAPITAL
#define VK_MOD_32 VK_OEM_2 // #' button on german keyboard
#define VK_MOD_41 VK_OEM_102 // <>| button on german keyboard
#define VK_MOD_42 VK_RMENU

#define VK_0 48
#define VK_1 49
#define VK_2 50
#define VK_3 51
#define VK_4 52
#define VK_5 53
#define VK_6 54
#define VK_7 55
#define VK_8 56
#define VK_9 57

#define VK_A 65
#define VK_B 66
#define VK_C 67
#define VK_D 68
#define VK_E 69
#define VK_F 70
#define VK_G 71
#define VK_H 72
#define VK_I 73
#define VK_J 74
#define VK_K 75
#define VK_L 76
#define VK_M 77
#define VK_N 78
#define VK_O 79
#define VK_P 80
#define VK_Q 81
#define VK_R 82
#define VK_S 83
#define VK_T 84
#define VK_U 85
#define VK_V 86
#define VK_W 87
#define VK_X 88
#define VK_Y 89
#define VK_Z 90

#define VK_UE 186
#define VK_PLUS 187
#define VK_COMMA 188
#define VK_DASH 189
#define VK_DOT 190
#define VK_HASH 191 // #
#define VK_OE 192
#define VK_SZ 219
#define VK_CIRCUMFLEX 220
#define VK_ACUT 221
#define VK_AE 222
#define VK_SMALLER 226
